### ISSUE TITLE
libuv filesystem async calls

### ISSUE THREAD

**Issue by pohmelie** [MagicStack/uvloop#1]
AFAIK, libuv also support async filesystem calls. Can this be implemented in uvloop (or based on uvloop) with nice `await with` and some `pathlib` awaitable coroutines? If so, «not good» executors for filesystem calls can be dropped :clap:

**Comment by 1st1** [comment]
Yes, once I'm done with adding/testing the basic APIs, we'll experiment with files ;)

**Comment by pohmelie** [comment]
Great!

**Comment by GMLudo** [comment]
For my information, behind the scenes, it uses what on Linux? Threads?

**Comment by 1st1** [comment]
It uses threads on all platforms -- that's the only reliable way.

**Comment by pohmelie** [comment]
@1st1 hm, if so, is there any profit of use libuv for file io?

**Comment by 1st1** [comment]
I've no idea. I think it will be a bit faster, since IO threadpool in libuv is implemented in C (compared to pure Python executors in asyncio).

**Comment by pohmelie** [comment]
@1st1 sounds right. And I answer my question: this will be the only solution (with nice syntax of course), since AFAIK there is no async filesystem library in python except [aiofiles](https://github.com/Tinche/aiofiles) (but this have no path operations).
Thanks for great project! :+1:

**Comment by saghul** [comment]
FWIW, the current builtin threadpool just has 4 threads.

**Comment by 1st1** [comment]
@saghul Is that usually enough (I assume `getaddrinfo` uses the same threadpool)? Would be great to have an API call to change the size, instead of the `UV_THREADPOOL_SIZE` env var...

**Comment by saghul** [comment]
So far it has been... unless you use it for long running blocking operations like talking to serial devices. We have plans to improve it, but no real ETA.

**Comment by GMLudo** [comment]
@saghul: a filesystem stored on a slow SAN because it's overloaded, could also be considered as a long running blocking operation like serial, or not?

**Comment by saghul** [comment]
Yep.

**Comment by 1st1** [comment]
@GMLudo That's not a problem atm, since uvloop doesn't have any methods to work with files.

**Comment by 1st1** [comment]
I'll just close this.  First async file IO must be implemented in asyncio directly.
