### ISSUE TITLE
Can't leave host=None in loop.create_server

### ISSUE THREAD

**Issue by scottruss** [MagicStack/uvloop#10]
With release 0.4.11, if you leave host=None while setting the port with create_sever() you end up with:

  File "uvloop/loop.pyx", line 1028, in create_server (uvloop/loop.c:19317)
  File "uvloop/loop.pyx", line 511, in uvloop.loop.Loop._getaddrinfo (uvloop/loop.c:12089)
TypeError: host must be a str or bytes

This is different behavior from the base asyncio create_server that allows host=None while setting the port.

**Comment by 1st1** [comment]
Thanks for reporting this. I'm working on a fix.

**Comment by 1st1** [comment]
Should be fixed in 448eea338ae4b07dbf0afc5dd00593164531e482, will soon release a new version.

**Comment by 1st1** [comment]
Please try uvloop 0.4.12.

**Comment by 1st1** [comment]
Closing this issue. Update it if the issue still isn't fixed in 0.4.13.
