### ISSUE TITLE
In python 3.6.2, I can't use uvloop in asyncio

### ISSUE THREAD

**Issue by Sherlock-Holo** [MagicStack/uvloop#107]
* **uvloop version**:0.8.0
* **Python version**:3.6.2
* **Platform**:arch linux x64
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**:

This is my code [asyncio can't use uvloop](https://gist.github.com/Sherlock-Holo/468b85feca5599f9baab0df65c64cd13), I try it on my server with python 3.5 and it works well, I guess uvloop doesn't support python 3.6 well, what should I do to make my codes runs on python 3.6

**Comment by Sherlock-Holo** [comment]
I install it by [AUR python-uvloop](https://aur.archlinux.org/packages/python-uvloop/)

**Comment by mosajjal** [comment]
I recommend using a `virtualenv` and installing it with pip. Works perfectly for me.

```
$ python3 -m venv uvloop-venv
$ cd uvloop-venv
$ source bin/activate
$ pip install uvloop
```

**Comment by Sherlock-Holo** [comment]
I used Arch official repo libuv and then `build_ext --use-system-libuv`
`build_py`, now I can installed it on my Arch. I written a comment about it
on aur python-uvloop waiting for maintainer reply me.

Alireza Mosajjal <notifications@github.com>于2017年9月11日周一 下午8:27写道：

**Comment by 1st1** [comment]
Look like this isn't a uvloop issue, but rather that it's related to Arch packaging. Closing this, feel free to reopen.
