### ISSUE TITLE
create_datagram_endpoint does not work with IPv6

### ISSUE THREAD

**Issue by chrysn** [MagicStack/uvloop#108]
* **uvloop version**: 0.8.1
* **Python version**: 3.5.4rc1
* **Platform**: Debian GNU/Linux
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: yes

While the default asyncio main loop can easily accept both IPv4 and IPv6 addresses n `create_datagram_endpoint(remote_addr=...)`, uvloop accepts IPv4 address only.

The [attached example](https://github.com/MagicStack/uvloop/files/1298789/echo.py.txt) shows this; call it `./echo.py 0 127.0.0.1` and `./echo.py 0 ::1` to use asyncio's main loop and try to reach localhost:9999 (usually gives you "Connection refused" errors for both). Running it as `./echo 1 127.0.0.1` sends the datagram using uvloop (it doesn't show an error, but that's probably a different bug), and running it as `./echo 1 ::1` tries IPv6 on uvloop, but raises a `socket.gaierror: [Errno -9] Address family for hostname not supported`.

The example is almost verbatim the [example from the Python documentation](https://docs.python.org/3/library/asyncio-protocol.html#udp-echo-client-protocol), adapted to take arguments and start uvloop.

**Comment by chrysn** [comment]
More precisely, it does not work *without further options* with IPv6; setting `family=AF_INET6` does make a `::1` connection work, but then again doesn't allow v4 addresses to be used without prior inspection of the address for which family to set. Passing `flags=socket.AI_V4MAPPED` in addition to family creates a default behavior that seems to be equivalent to asyncio's. (asyncio claims that it decides based on `host`'s value which family it chooses; I did not verify that, and only looked at the simple test's behavior).

**Comment by 1st1** [comment]
> asyncio claims that it decides based on host's value which family it chooses

Alright, I'll take a look how Python/asyncio implements that.

**Comment by 1st1** [comment]
BTW, feel free to submit a PR if you have a good idea how to fix this before I find time.

**Comment by 1st1** [comment]
Fixed in master.  Will be in the next uvloop release next week.

**Comment by 1st1** [comment]
Please try uvloop v0.9.0!
