### ISSUE TITLE
UDP "port unreachable" is not exposed

### ISSUE THREAD

**Issue by chrysn** [MagicStack/uvloop#109]
* **uvloop version**: 0.8.1
* **Python version**: 3.5.4rc1
* **Platform**: Debian GNU/Linux
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: yes

The [example](https://github.com/MagicStack/uvloop/files/1298789/echo.py.txt) from issue #108, when run as `./echo.py 0 127.0.0.1` (running an [example from the Python documentation](https://docs.python.org/3/library/asyncio-protocol.html#udp-echo-client-protocol) in asyncio, which opens a UDP socket to an unserviced port and sends data) reports an OSError 111 "Connection refused", while when run as `./echo.py 1 127.0.0.1` (picking uvloop as the main loop), the network error is silently ignored.

Please make uvloop call error_received with some exception in those situations.

(This was already hinted at in https://github.com/MagicStack/uvloop/issues/108, but I opened it as a separate issue so its resolution can be tracked by the workarounds for this just entering the aiocoap test suite).
[edit: missed the platform field]

**Comment by 1st1** [comment]
Should be fixed in master.  Can you test if UDP works for you guys now?

**Comment by 1st1** [comment]
Please try uvloop v0.9.0, where this bug should be fixed.
