### ISSUE TITLE
Fails to install with Python 3.7

### ISSUE THREAD

**Issue by JulienPalard** [MagicStack/uvloop#110]
* **uvloop version**: 0.8.1
* **Python version**: 3.7a1
* **Platform**: Debian 9.1
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: Not relevant

Uvloop fails to install from pypi with Python 3.7 as the PyCFunctionFast signature has changed. It has been fixed in cython 0.26.1.

**Comment by industrialsynthfreak** [comment]
I can confirm. No difference on Sierra for both 0.7.x and 0.8.x.

**Comment by 1st1** [comment]
Fixed in master. Will be in the next uvloop release (0.9.0) soon. Keep in mind that Cython isn't compatible with 3.7.0a2 yet, so we'll only have 3.7.0a1 compatibility.

**Comment by 1st1** [comment]
v0.9.0 should be compatible with 3.7.0a1

**Comment by cjrh** [comment]
Verified, works against Python nightly in one of my projects :100:
