### ISSUE TITLE
Implement set_child_watcher in uvloop policy

### ISSUE THREAD

**Issue by asvetlov** [MagicStack/uvloop#112]
`AbstractEventLoopPolicy.set_child_watcher()` is part of asyncio protocol.

See aio-libs/aiohttp#2491 for details

**Comment by 1st1** [comment]
I think I'll keep `set_child_watcher` non implemented. Windows policy doesn't implement it, which suggests us that it's OK for a working policy to not support this API.  So my advice is to simply handle `NotImplementedError`.
