### ISSUE TITLE
Request for uvloop 1.0 release

### ISSUE THREAD

**Issue by asvetlov** [MagicStack/uvloop#115]
The library is pretty stable.
I trust it personally.
But `1.0` version number is the sign of officially supported stability. Sometimes people are scared about `0.xxx` version numbers.

My story. 
Almost two ears ago at EuroPython people asked me: "Why aiohttp has a release number `0.22`? Is it stable or not?"
Just after the conference we've released aiohttp 1.0. No dramatic changes and no significant API improvements IIRC -- but just a sign for library maturity.

I pretty sure the next uvloop should be a major stable release `1.0`.

**Comment by 1st1** [comment]
I plan to make a few changes to internals that can potentially require a few rounds of bugfix releases.  Let's release 0.9.x, give it a month and release 1.0 after that.

**Comment by asvetlov** [comment]
Works for me.
Feel free to close the issue.

**Comment by 1st1** [comment]
Thanks, Andrew
