### ISSUE TITLE
SIGCHLD not reaped by uvloop when using subprocess protocol

### ISSUE THREAD

**Issue by byllyfish** [MagicStack/uvloop#128]
* **uvloop version**: 0.9.1
* **Python version**:  3.6.3
* **Platform**:  OS X High Sierra
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: Yes

I'm seeing a difference of behavior between the default asyncio event loop and uvloop when using a subprocess. When my code closes a subprocess transport under uvloop, the protocol's connection_lost handler is not called.  The child process continues to show up in 'ps' output as a zombie.

The same behavior happens under ubuntu linux 16.04, with python 3.5.2.

The source code for 'test_subprocess.py' is below. 

uvloop output:

```shell
$ python3 test_subprocess.py
connection_made
pipe_connection_lost 0
pipe_connection_lost 1
pipe_connection_lost 2

```

asyncio output:

```shell
 $ NO_UVLOOP=1 python3 test_subprocess.py
connection_made
pipe_connection_lost 0
pipe_connection_lost 1
pipe_connection_lost 2
process_exited
connection_lost
```

test_subprocess.py:

```python
import asyncio
import os
import uvloop

if 'NO_UVLOOP' not in os.environ:
    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())


class Protocol(asyncio.SubprocessProtocol):

    def __init__(self):
        self.closed = asyncio.get_event_loop().create_future()

    def connection_made(self, transport):
        print('connection_made')
        
    def connection_lost(self, exc):
        print('connection_lost')
        self.closed.set_result(1)

    def pipe_connection_lost(self, fd, exc):
        print('pipe_connection_lost', fd)

    def process_exited(self):
        print('process_exited')


async def test_subprocess(loop):
    transport, protocol = await loop.subprocess_exec(Protocol, '/bin/cat')
    transport.close()
    await protocol.closed


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(test_subprocess(loop))
```

**Comment by byllyfish** [comment]
If I replace the line `transport.close()` with any of the following, the code runs fine under uvloop:

1. transport.kill()
2. transport.terminate()
3. transport.get_pipe_transport(0).close()

Looking at the code for UVProcessTransport.close (uvloop/handles/process.pyx), does self._close() close the libuv internal handle *before* it has had a chance to reap the child process?

```python
    def close(self):
        if self._returncode is None:
            self._kill(uv.SIGKILL)

        if self._stdin is not None:
            self._stdin.close()
        if self._stdout is not None:
            self._stdout.close()
        if self._stderr is not None:
            self._stderr.close()

        self._close()
```

uvloop Issue #64 ("asyncio.get_child_watcher Not Working" ) is similar to this one. I think there's a race condition in the sample code provided, which is why it may not have been reproducible.

**Comment by 1st1** [comment]
Yeah, there's definitely a bug here. I don't have time to look at this right now 😞, but feel free to submit a PR.

**Comment by 1st1** [comment]
Well, one obvious solution is to simply remove `self._close()` line. The handler will be properly closed in its `__dealloc__`.  I'm going to try this.
