### ISSUE TITLE
Any plan combining uvloop with aiohttp?

### ISSUE THREAD

**Issue by laike9m** [MagicStack/uvloop#13]
Or is it possible now?

**Comment by 1st1** [comment]
Yes, just put these lines

```python
import asyncio
import uvloop
asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
```

in the very beginning of your program and it will run on uvloop. aiohttp will run too.

**Comment by sjatkins** [comment]
I tried this and it resulted in an unstarted loop.  I am not sure why.
