### ISSUE TITLE
Expose `Loop._thread_id`

### ISSUE THREAD

**Issue by blakev** [MagicStack/uvloop#130]
* **uvloop version**: 0.9.1 (libuv 1.19.2-1)
* **Python version**: 3.5.5
* **Platform**: Linux 4.15.7-1-ARCH
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: Yes

I cannot read `_thread_id` from the `uvloop.Loop` instance to help with deterministic scheduling. Even though it's protected, you can read the attribute from the `asyncio` default loop.

Consider,

```python
import asyncio
import uvloop

loop = asyncio.new_event_loop()
print(loop._thread_id)

loop = uvloop.new_event_loop()
print(loop._thread_id)
```

**Comment by 1st1** [comment]
What is "deterministic scheduling"? There are absolutely no guarantees that `_thread_id` will be exposed in future asyncio releases, it's a protected non-documented property. I usually don't want to make uvloop compatible on that level.

**Comment by blakev** [comment]
Events are scheduled differently if we're on the MainThread. I'm not sure how to check which thread the loop is running on without accessing that attribute.

**Comment by 1st1** [comment]
Well, generally you should just use `loop.call_soon_threadsafe` and `asyncio.run_coroutine_threadsafe`. Without you providing more details I cannot help you any further.

**Comment by blakev** [comment]
```python
if threading.get_ident() != self.loop._thread_id:
    self.logger.debug("calling from a different Thread")
    self.handle = self.loop.call_soon_threadsafe(self.__threaded_call__)
else:
    self.handle = self.loop.call_later(self.delay, self.run)
```
