### ISSUE TITLE
Server object in uvloop and asyncio

### ISSUE THREAD

**Issue by janhn** [MagicStack/uvloop#131]
* **uvloop version**: 0.9.1
* **Python version**: 3.5.2

Writing some unit tests using create_server() and trying to check the resulting
object, the object hierarchy differs between asyncio and uvloop. The following
will fail with uvloop:

```python
server = loop.create_server(factory, host, port)
assert isinstance(server, asyncio.AbstractServer)
```

Wouldn't it make sense for uvloop to have its Server class inherit from the same base?

**Comment by 1st1** [comment]
Unfortunately this isn't something that we can do in Cython (at least the support is very limited in 0.28.2). Many of uvloop objects are defined as extension types which cannot be derived from Python classes. A better option is to simply use duck typing.

**Comment by asvetlov** [comment]
Theoretically, we can modify asyncio abstract classes to be real ABCs like `collection.abc`.
@1st1 do you think it makes sense?

**Comment by 1st1** [comment]
Then isinstance checks will be slow. TBH there's little use case to actually use `isinstance(s, AbstractServer)` or `isinstance(s, Transport)`. Do you know a good real-world use case?

**Comment by asvetlov** [comment]
No, I'm thinking mainly about introspection. 
Abstract base classes from collections are also slow, but I found them very useful.
At least I always derive from proper ABC when developing a new data structure class.
Perhaps correct class hierarchy is something that would be nice to have.

**Comment by 1st1** [comment]
Maybe. Feel free to open an asyncio feature request for 3.8. We'll need to check if we actually call `isinstance` in asyncio so that we don't harm the performance.
