### ISSUE TITLE
uvloop with asyncio.Event

### ISSUE THREAD

**Issue by alpha-86** [MagicStack/uvloop#134]
* **uvloop version 0.9.1:
* **Python 3.6.4:
* **Platform centos 7.4.1708:
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**:

When I use uvloop,then I got this problem.
the self._event is asyncio.Event

File "/home/work/work/inflight/base.py", line 25, in wait
    return await self._event.wait()
  File "/usr/lib64/python3.6/asyncio/locks.py", line 271, in wait
    yield from fut
RuntimeError: Task <Task pending coro=<BasicInflight.loop() running at /home/work/work/inflight/basic.py:506> cb=[gather.<locals>._done_callback(4)() at /usr/lib64/python3.6/asyncio/tasks.py:616]> got Future <Future pending> attached to a different loop

If I remove uvloop,there is no problem.

**Comment by 1st1** [comment]
This seems to be a bug in your code that accidentally works under vanilla asyncio. Hard to say more without seeing a code snippet that reproduces this.

**Comment by asvetlov** [comment]
I bet @alpha-86 creates `asyncio.Event()` in module global scope *before* installing uvloop.

**Comment by 1st1** [comment]
Yeah, you're right, that's what it seems to be

**Comment by alpha-86** [comment]
thanks，I found asyncio.Event() was creates in global scope.

I have fix this problem
