### ISSUE TITLE
taking uvloop into production?

### ISSUE THREAD

**Issue by digitaldavenyc** [MagicStack/uvloop#15]
This is not an issue but perhaps a request to maybe expand on documentation on how to use uvloop with other frameworks. The performance on it is very impressive, however, it's so low level, taking this into a production application would be quite a challenge.

What would be the best practice approach to doing this? Combine with tornado or any other async libary? Leverage other smaller libraries to handle things like user authentication and http parsing. Or does uvloop just need these features introduced directly into it to maintain the performance it currently has?

If I am using the wrong forum for asking this question I apologize and happy to move this discussion somewhere else.

**Comment by 1st1** [comment]
> What would be the best practice approach to doing this? Combine with tornado or any other async libary?

uvloop only works with [asyncio](https://docs.python.org/3/library/asyncio.html#module-asyncio). It cannot work with Tornado, gevent, curio, or any other async Python library other than asyncio.

> Leverage other smaller libraries to handle things like user authentication and http parsing. Or does uvloop just need these features introduced directly into it to maintain the performance it currently has?

asyncio is an async library that implements many low-level and high-level abstractions. It has Protocols and Transports, helpers to create network servers and clients, etc. I highly recommend you to glance over the documentation.

asyncio is built around the event loop. That's the thing that runs asyncio. uvloop is an implementation of a fast event loop for asyncio.

Now, asyncio, by itself, doesn't provide any high-level tools for you to write applications. For instance, it lacks an HTTP protocol implementation, etc.  You need other libraries built for asyncio to do that for you.  For HTTP, right now, there is [aiohttp](http://aiohttp.readthedocs.io/en/stable/).  There are many other libraries for working with databases, using AMQP brokers, etc.

> The performance on it is very impressive, however, it's so low level, taking this into a production application would be quite a challenge.

Once you have an asyncio application, speeding it up with uvloop is very easy -- just install the uvloop policy (see the README file).

**Comment by digitaldavenyc** [comment]
> I highly recommend you to glance over the documentation.

Do you mean I should review uvloop's documention or asyncio's?

> You need other libraries built for asyncio to do that for you. For HTTP, right now, there is aiohttp.

In your [blog post](http://magic.io/blog/uvloop-blazing-fast-python-networking/) you mentioned that the performance in [aiohttp](http://aiohttp.readthedocs.io/en/stable/) was pretty bad with uvloop due to the HTTP parser. Wouldn't [httptools](https://github.com/MagicStack/httptools) be the prefered library for handing HTTP requests?

**Comment by 1st1** [comment]
> Do you mean I should review uvloop's documention or asyncio's?

asyncio documentation to get a better idea of what it's capable of.

> In your blog post you mentioned that the performance in aiohttp was pretty bad with uvloop due to aiohttp's HTTP parser. Wouldn't httptools be the prefered library for handing HTTP requests?

Right. The httptools package at this moment doesn't provide an implementation of HTTP, it only has a high-performance parser.  So right now, aiohttp is the only option, but I hope its newly discovered performance issues will be fixed soon (by incorporating httptools or somehow else).

**Comment by digitaldavenyc** [comment]
There was already an issue open over at [aiohttp](http://aiohttp.readthedocs.io/en/stable/) for swapping out the http parser for [httptools](https://github.com/MagicStack/httptools). If this could be done in the near future both libraries could be thrown into the spotlight. Being able to stay on the same performance level with Go is huge. Thank you so much for contributing this library to the community!

**Comment by 1st1** [comment]
Thanks!
Closing this issue.
