### ISSUE TITLE
SSLProtocol stalled during handshake

### ISSUE THREAD

**Issue by hynek** [MagicStack/uvloop#161]
* **uvloop version**:

0.10.0, doesn’t happen with 0.9.1

* **Python version**:

3.6.5

* **Platform**:

Ubuntu Xenial/Docker

* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**:

Yes, but I get no additional output.

***

I have to communicate with a super-slow endpoint and since 0.10.0, the connection doesn’t go thru and aborts before the timeout I specify.

Stdout gets a string like: `<uvloop.loop.SSLProtocol object at 0x7f227a1a1048> stalled during handshake`. It seems like there’s a second timeout in play? I did measure the handshake by hand I would guess something around 5s.

Downgrading back to 0.9.1 fixes the problem.

P.S. Bonus bug I cannot handily reproduce: sometimes I saw an AttributeError about `errno` not being on `CertificateError` or something like that.

**Comment by 1st1** [comment]
In 0.10.0 there's a 10 seconds timeout for the handshake operation. Is your endpoint slower than that?

It's also a default timeout for handshake in asyncio 3.7, although it's configurable via the `ssl_handshake_timeout` parameter to `create_connection` and `create_server` (the parameter isn't yet backported to uvloop).  Do you feel that 10 seconds is not enough?

> P.S. Bonus bug I cannot handily reproduce: sometimes I saw an AttributeError about errno not being on CertificateError or something like that.

That means asyncio 3.7 has this bug too. Will take a look.

**Comment by hynek** [comment]
> Do you feel that 10 seconds is not enough?

How do you think I found out? ;) 10s is wayyy to short once you have to communicate from/to Africa or Asia. I spent a month in Cape Town and learned this the hard way.

In this case I couldn’t communicate with a server in India. If this goes into 3.7 there’s gonna be a lot of...reports. :D

**Comment by 1st1** [comment]
What default timeout would you suggest?

> It would also be great if we could do something about the output btw.

You mean the errno/CertificateError error? Or the "... stalled during handshake" error message?

**Comment by hynek** [comment]
> What default timeout would you suggest

No clue! Check what browsers or Java or Go do maybe?

> You mean the errno/CertificateError error? Or the "... stalled during handshake" error message?

Both ✨ 

Although the errno thing is a lot more severe.

**Comment by hynek** [comment]
(I can live with it staying at 10s btw as long as you give me a knob to turn. :))

**Comment by 1st1** [comment]
(a PR to CPython to fix this: https://github.com/python/cpython/pull/7321)

**Comment by 1st1** [comment]
Fixed in v0.10.1. Please try it ;)

**Comment by hynek** [comment]
Happy to report I can connect to India again. :)
