### ISSUE TITLE
uvloop SSL connections unnecessarily calls loop exception handler

### ISSUE THREAD

**Issue by elprans** [MagicStack/uvloop#164]
* **uvloop version**: 0.10.1
* **Python version**: 3.5.5, 3.6.5
* **Platform**: Linux

`pytest -k test_ssl_connection_default_context` in asyncpg started failing because 0.10.1 unnecessarily logs `SSLError` that it has already thrown into `connection_lost`

See https://travis-ci.org/MagicStack/asyncpg/jobs/386904645#L1639

**Comment by 1st1** [comment]
This is how asyncio works for regular transports and how it will work for SSL transports in 3.7. Note how most errors are logged in `selector_events.py` even though they are propagated to a protocol:

https://github.com/python/cpython/blob/9602643120a509858d0bee4215d7f150e6125468/Lib/asyncio/selector_events.py#L669-L681
