### ISSUE TITLE
compile uvloop: virtual memory exhausted

### ISSUE THREAD

**Issue by Sherlock-Holo** [MagicStack/uvloop#167]
* **uvloop version**:0.10.1
* **Python version**:3.6
* **Platform**:amd64
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**:

When I compile the uvloop on my arch linux(not my laptop, on my virtual server), it reports 
```
running build_ext
uvloop/loop.pyx: cannot find cimported module '.includes'
uvloop/loop.pxd: cannot find cimported module '.includes'
Compiling uvloop/loop.pyx because it changed.
[1/1] Cythonizing uvloop/loop.pyx
building 'uvloop.loop' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/uvloop
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector
-strong -fno-plt -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c uvloop/loop.c -o build/temp.linux-x86_64-3.6/uv
loop/loop.o -O2
virtual memory exhausted: 无法分配内存
error: command 'gcc' failed with exit status 1
```
Is my VPS mem too small? I reboot it and now it seems compiling and it eats 413+102MB mem.

**Comment by 1st1** [comment]
Yeah, I don't think anything can be done here except increasing the amount of memory for your VM. I'd suggest using wheels to avoid the compilation step (simple `pip install uvloop` should just install a pre-compiled wheel package for you).

**Comment by Sherlock-Holo** [comment]
oh, it compiles failed again, 😂 I have to compile on my PC, and succeed.
so sad for my small memory VPS😂

Yury Selivanov <notifications@github.com> 于 2018年6月6日周三 05:14写道：

**Comment by jakewaxman** [comment]
Had this problem on a 1GB droplet.
Creating a swapfile took care of it.
Used instructions at https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-18-04
