### ISSUE TITLE
uvloop install fail in docker w/ pip install

### ISSUE THREAD

**Issue by pepie** [MagicStack/uvloop#168]
Hello! Trying to install uvloop in a python app within a docker image.
I am currently getting the following errors (below).

* **uvloop version**: latest
* **Python version**: 3.7
* **Platform**: Docker (python:alpine3.7)
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**:
haven't tried

unable to install uvloop in docker, the same configuration works outside of the container.
requirements.txt:
`asyncio
uvloop
asyncpg
`
Dockerfile:
`RUN python3 -m pip install -r requirements.txt`

Error:

`Collecting uvloop (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/d4/50/385f5dfd008508750a255ae742aaea6cc7f58877d9444b2d759543b0ee72/uvloop-0.10.1.tar.gz (1.9MB)
Collecting asyncpg==0.16.0 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/89/62/6d218bc7d1412b837ed6f006a42a660fc970c3135c22c55f2370a93e11d4/asyncpg-0.16.0.tar.gz (615kB)
    Complete output from command python setup.py egg_info:
    error in asyncpg setup command: 'extras_require' requirements cannot include environment markers, in 'test': 'uvloop>=0.8.0; platform_system != "Windows"'
`

again, the same requirements file work outside of docker (mac os + python 3.6)

**Comment by elprans** [comment]
Try `pip install -U setuptools pip` before.

**Comment by sakurai-youhei** [comment]
Probably Cython needs to be installed before installing uvloop.

**Comment by 1st1** [comment]
> Probably Cython needs to be installed before installing uvloop.

No. Cython is only used during the sdist/bdist phases. It's not a runtime dependancy.

Closing this issue.

**Comment by japrogramer** [comment]
Im having this issue the image is and as you can see im updating setuptools and pip before trying to install from requirements.

```
FROM python:3.7.0-alpine3.8
RUN apk update \
    && apk add python3 postgresql-libs \
    && apk add --update --no-cache --virtual .build-deps alpine-sdk python3-dev musl-dev postgresql-dev libffi-dev \
    && pip install -U setuptools pip \
    && pip install --no-cache-dir -r /requirements/local.txt \
    && rm -rf /requirements \
    && apk --purge del .build-deps

```

**Comment by vproman** [comment]
Run this command to recreate issue:
docker run python:3.7 pip install uvloop==0.8

As a workaround, you can either use python 3.6 instead:
docker run python:3.6 pip install uvloop==0.8

Or you can update uvloop to at least v0.9:
docker run python:3.7 pip install uvloop==0.9

**Comment by Recro-Barry** [comment]
@1st1 is there another issue that addresses this topic? The issue got closed without addressing the main problem at all.

**Comment by elprans** [comment]
The original issue is a setuptools bug. Do a `pip install -U setuptools` before installing uvloop.

**Comment by saitaro** [comment]
> The original issue is a setuptools bug. Do a `pip install -U setuptools` before installing uvloop.

It doesn't solve the problem for me :/

**Comment by Alex-CodeLab** [comment]
this worked for me
`apk add alpine-sdk`

**Comment by EvertonSA** [comment]
> this worked for me
> `apk add build-base`

This should be in somewhere in the documentation as a requirement for using uvloop in alpine docker images

**Comment by OpetherMB** [comment]
> Try `pip install -U setuptools pip` before.

thank you very much

**Comment by ronsinai** [comment]
> this worked for me
> `apk add build-base`

Is it mandatory for running the app (with `uvloop.install()`) or could be deleted following `pip install uvloop`?

**Comment by Mathdrquinn** [comment]
> The original issue is a setuptools bug. Do a `pip install -U setuptools` before installing uvloop.

Thank you for the note!  Could you describe or link to the bug?

**Comment by galimk** [comment]
In the end downgrading the alpine linux version from 3.15 to 3.13 helped me.

https://stackoverflow.com/a/68798160

**Comment by wukaka** [comment]
> In the end downgrading the alpine linux version from 3.15 to 3.13 helped me.
> 
> https://stackoverflow.com/a/68798160

worked!

**Comment by EvertonTomalok** [comment]
> Im having this issue the image is and as you can see im updating setuptools and pip before trying to install from requirements.
> 
> ```
> FROM python:3.7.0-alpine3.8
> RUN apk update \
>     && apk add python3 postgresql-libs \
>     && apk add --update --no-cache --virtual .build-deps alpine-sdk python3-dev musl-dev postgresql-dev libffi-dev \
>     && pip install -U setuptools pip \
>     && pip install --no-cache-dir -r /requirements/local.txt \
>     && rm -rf /requirements \
>     && apk --purge del .build-deps
> ```

It works for me! Thank a lot!

**Comment by orenwang** [comment]
For me, I had to add both `python3-dev` & `build-base`:

```
FROM alpine:3.16
RUN apk add --no-cache python3
RUN apk add --no-cache python3-dev
RUN apk add build-base
```

**Comment by Lx** [comment]
Probably much too late for @ronsinai, but for anyone else who got here from a Google search:

> > this worked for me
> > `apk add build-base`
> 
> Is it mandatory for running the app (with `uvloop.install()`) or could be deleted following `pip install uvloop`?

`build-base` is not a runtime requirement.  It **can** be deleted following `pip install uvloop`.
