### ISSUE TITLE
asyncio.base_futures.InvalidStateError: invalid state

### ISSUE THREAD

**Issue by andr-04** [MagicStack/uvloop#169]
* **uvloop version**: 0.10.1
* **Python version**: 3.6.5
* **Platform**: Ubuntu 16.04
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: No

I work with a raw sockets using `asyncio.Lock` to isolate blocks reading and `sock_recv` to communicate inside a Lock section.
In a random time first of all I get the following stacktrace:
```
Exception in callback Loop._sock_recv
handle: <Handle Loop._sock_recv>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 76, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 888, in uvloop.loop.Loop._sock_recv
asyncio.base_futures.InvalidStateError: invalid state
```

After that there is a problem with acquiring the Lock: it becomes pass any simultaneously calls.

Now very small information, but I'll try to investigate and reproduce it. And give you more details. But maybe you have a thoughts already?

**Comment by andr-04** [comment]
Ok, I compare the implementation with base loop one and see you don't check does the future is cancelled or not yet. It's bad because it's a real usecase to wrap `sock_recv ` by `asyncio.wait` with a timeout.

**Comment by 1st1** [comment]
Would you mind making a PR fixing this?

**Comment by andr-04** [comment]
Well, I've understood the behaviour and Lock is not a problem there at all; the problem is __shifting__ in the source data structure: before exception we read the data which already is related with other caller.
I didn't use Cython in real life yet and I'm aware it will take a lot of time to make a fix, check it and write unit tests for it. Especially I've not done it [there](https://github.com/python/cpython/pull/4386#issuecomment-344261746).

But I can to try later.

**Comment by andr-04** [comment]
Moved to PR #170.

**Comment by 1st1** [comment]
Regarding #170: I don't think that copying the approach of `asyncio/base_events.py` is the right strategy here. IIRC I decided to go with a different implementation of `loop.sock_*` methods because asyncio has many other problems with cancellation.  In uvloop, cancellation happens in `_new_reader_future` and `_new_writer_future` methods, maybe they should be adjusted to handle your case?

BTW, I don't see a unittest to reproduce the bug you're trying to fix.  It's absolutely crucial to have a unittest, can you please try to come up with one?

**Comment by andr-04** [comment]
Well, it more difficult to reproduce than I thought before. I've investigated the problem by write the sequence of operations to the log.

The normal pipeline with timeouts are:
1. `await sock_recv`;
2. `_on_cancel` callback from previously timeout `sock_recv`;
3. `_remove_reader` called by `_on_cancle` callback;
4. `_add_reader` called by the last `await sock_recv`;
5. interrupting `await sock_recv` by timeout with calling `fut.cancel()`.

In the InvalidStateError the sequence a little bit differ: before `_on_cancel` we get `_sock_recv`. So, due to the previous future from `await sock_recv` is cancelled, but the data from socket has read, so it is completely lost. Another question which I have -- even if I add a check the result future must not be cancelled (i.e. if it cancelled just return from `_sock_recv` without reading), the new `_add_reader` does not raise `_sock_recv` for old data which was given, but not read yet. I really don't know why. Any ideas?

As a solution I suggest to make a subclass from the base `Event` and redefine `cancel` method of it to make this part of code be synced. What the name you would like I give for it and what are your views for this solution at all?

And yes, I'm unable to write unit test for it.
