### ISSUE TITLE
Suppress messages

### ISSUE THREAD

**Issue by frnkvieira** [MagicStack/uvloop#175]
```py 
import asyncio
import ssl
import uvloop


async def connect():
    try:
        await asyncio.open_connection(host='expired.badssl.com', port=443, ssl=True)
    except ssl.SSLError:
        return

if __name__ == '__main__':
    # loop = asyncio.new_event_loop()
    # loop.run_until_complete(connect())
    loop = uvloop.new_event_loop()
    loop.run_until_complete(connect())
```

* **uvloop version**: 0.10.2
* **Python version**: 3.6.5
* **Platform**: Linux (Ubuntu 18.04 - Kernel 4.15)
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: Yes

I'm not sure if this is a bug but uvloop seems to be writing to stderr at some SSL exceptions (AFAIK asyncio don't do this), there is a way to suppress these messages? 

Many thanks for this **awesome** project!

**Comment by 1st1** [comment]
uvloop's SSL implementation is now the same as in Python 3.7, so both vanilla asyncio and uvloop should have the same logging behavior. If you think that logging is redundant in this case, please open an issue on bugs.python.org so that we fix it in both places.

Thanks!

**Comment by frnkvieira** [comment]
Fair enough, thanks!
