### ISSUE TITLE
Server fails to shutdown while persistent connections exist

### ISSUE THREAD

**Issue by ciscorn** [MagicStack/uvloop#180]
I noticed that a aiohttp server with uvloop==0.11.0 waits until all connections (WebSocket, streaming, etc.) are closed. This behavior prevents us from performing [aiohttp's graceful shutdown](https://docs.aiohttp.org/en/stable/web_advanced.html#graceful-shutdown).

This problem doesn't occur with uvloop==0.10.2.

I'm suspecting the commit 124e981bc90fbe2814dd1efd051e5b5a394cf1df because this change seems not to conform the following spec:

> asyncio.Server.close()
> Stop serving: close listening sockets and set the sockets attribute to None.
> **The sockets that represent existing incoming client connections are left open.**

**Comment by 1st1** [comment]
Can you submit a PR to revert that commit and maybe write a unittest?

**Comment by ciscorn** [comment]
I wrote a test and reverted the 124e981bc90fbe2814dd1efd051e5b5a394cf1df, but the problem still exists.
I'll investigate further and write a PR.

**Comment by 1st1** [comment]
Thanks!

**Comment by pvizeli** [comment]
Can we have a bugfix release?

**Comment by 1st1** [comment]
Fixed in uvloop 0.11.1. Thanks for working on this!
