### ISSUE TITLE
Explain why it is faster

### ISSUE THREAD

**Issue by oroulet** [MagicStack/uvloop#182]
in README and doc you write that you are faster than python included loop, but you say nowhere why (or at least it is well hidden). Did you reimplement things in C? did you you simply optimize code and patch are on their way to mainline? And why isn'it replacing the standard loop then? Must be some issues somewhere...If you want users to use it you should explain shortly these fundamental things

**Comment by sakurai-youhei** [comment]
Here is one sentence taken from README, which explains the reason well for me.

> uvloop is implemented in Cython and uses libuv under the hood.

**Comment by 1st1** [comment]
Closing this one. I also think that README and the linked blog post address this question just fine.
