### ISSUE TITLE
Could not build uvloop: uvloop/loop.c no such file or directory

### ISSUE THREAD

**Issue by sametmax** [MagicStack/uvloop#2]
Hi,

I tried to build the project to run the test on my machine (Ubuntu 14.04, 64b).

First I had to install automake and libtool (you may want to add this step on the readme), then running make I got:

        building 'uvloop.loop' extension
        creating build
        creating build/temp.linux-x86_64-3.5
        creating build/temp.linux-x86_64-3.5/uvloop
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/user/.local/share/virtualenvs/ace813a9968fde5/include/python3.5m -Ivendor/libuv/include -c uvloop/loop.c -o build/temp.linux-x86_64-3.5/uvloop/loop.o
        x86_64-linux-gnu-gcc: error: uvloop/loop.c: No such file or directory
        x86_64-linux-gnu-gcc: fatal error: no input files
        compilation terminated.
        error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
        make: *** [compile] Erreur 1

**Comment by 1st1** [comment]
The project isn't even in its "alpha" state right now ;)

To build you need cython, and to clone the repo with '--recursive'.  Then simply run "make"

**Comment by sametmax** [comment]
I just wanted to test it here to report failing test, hoping it would help you since I like the project. If you think it's too early for that, I can do that when the project is more mature. I don't want to add noise.

After installing cython, I could run the test and good news:

    $ make test
    PYTHONASYNCIODEBUG=1 python3 -m unittest discover -s tests
    .................................................
    ----------------------------------------------------------------------
    Ran 49 tests in 13.877s

    OK
    python3 -m unittest discover -s tests
    .................................................
    ----------------------------------------------------------------------
    Ran 49 tests in 1.992s

    OK

Let me know if you need me test more stuff :)

**Comment by 1st1** [comment]
I'm working on the project right now.  Have a bunch of changes to push.  I think we'll have an alpha pretty soon.

**Comment by sametmax** [comment]
Just pinging to get some news on the project. Again, if you need me to run tests on some machines, let me know.

**Comment by 1st1** [comment]
I'm a bit distracted by a few other projects, but I'm going to find some time to push uvloop to alpha soon. I need it for our core product in my firm, so be sure -- the project isn't dead ;)

**Comment by 1st1** [comment]
Closing this one.
