### ISSUE TITLE
UDPTransport AttributeError

### ISSUE THREAD

**Issue by amelchio** [MagicStack/uvloop#207]
* **uvloop version**: 0.11.2
* **Python version**: 3.6
* **Platform**: Linux
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: Unknown

This error was reported [in a forum post](https://community.home-assistant.io/t/lifx-integration-breaks-hass-io-how-to-revert/76610):
```
File “uvloop/handles/udp.pyx”, line 157, in uvloop.loop.UDPTransport.sendto
AttributeError: ‘uvloop.loop.UDPTransport’ object has no attribute ‘_address’
```
It seems like the attribute should be [`address`](https://github.com/MagicStack/uvloop/blob/v0.11.2/uvloop/handles/udp.pyx#L18), not [`_address`](https://github.com/MagicStack/uvloop/blob/v0.11.2/uvloop/handles/udp.pyx#L157).

**Comment by 1st1** [comment]
Thanks for submitting this. Care to make a PR?

**Comment by amelchio** [comment]
Not really. I am not set up for uvloop development and I don't even know how to reproduce the problem.

**Comment by jlaine** [comment]
This looks like a real bug, still present in the current code:

https://github.com/MagicStack/uvloop/blob/d5ad2b86fff1bf08a391aa344561e69c98be3b66/uvloop/handles/udp.pyx#L168
