### ISSUE TITLE
upgrade to libuv 1.25.0

### ISSUE THREAD

**Issue by wrobell** [MagicStack/uvloop#223]
libuv 1.24 and 1.25 removes potential security issues (use of `strncpy`)

   https://github.com/libuv/libuv/blob/v1.x/ChangeLog

as a side note: would be nice if the readme file showed how to install uvloop with pip and system libuv

**Comment by 1st1** [comment]
Yeah, that's blocked by https://github.com/libuv/libuv/issues/2058. We might need to fork libuv at this point (which will make it impossible to use the system libuv).  libuv maintainers aren't very responsive :(

**Comment by 1st1** [comment]
Alright, it appears that we can now migrate to new libuv: https://github.com/MagicStack/uvloop/pull/226

**Comment by wrobell** [comment]
Nice, thanks.

**Comment by jlaine** [comment]
I'm guessing this issue should be closed since d8fe153e5b67de1124b828f9c9b3c5397ac68d5d has landed?
