### ISSUE TITLE
Building on Raspberry Pi

### ISSUE THREAD

**Issue by wrobell** [MagicStack/uvloop#227]
I am using uvloop on Raspberry Pi Zero (many of them ;)). To upgrade to new version, due to memory limitations, one has to go through the following procedure

1. Stop as many applications as possible to free the memory.
2. Create 512M swap file (less might be required).
3. Start installation of `uvloop`.
4. Get coffee. ;)

As `uvloop` provides wheel files for several platforms, IMHO, it would be a great addition to have a wheel file for Raspberry Pi to avoid the above hassle. The target platform would be `armv6`.

**Comment by 1st1** [comment]
Care to make a PR to add it to our CI targets? :)

**Comment by jlaine** [comment]
A much better option is to coordinate with https://github.com/bennuttall/piwheels

The piwheels project is awesome, it automatically builds wheels for all packages on pypi, and makes them directly installable in the default raspbian distro.

uvloop up to and including 0.12.0 are available, not sure what's up with 0.12.1:

https://www.piwheels.org/simple/uvloop/

**Comment by wrobell** [comment]
According to https://www.piwheels.org, no Python 2.7, 3.6 and 3.7 at the moment (personally, I am using 3.7).

**Comment by jlaine** [comment]
Still my point remains that putting the effort on the piwheels side seems more relevant. Even if uvloop's CI produced wheels for Raspberry Pi, there would be no "right" place to upload them. PyPI would almost certainly not be the right place, see:

https://github.com/pypa/manylinux/issues/84

**Comment by 1st1** [comment]
Yeah, it seems that PyPI isn't the right place for hosting wheels for Pi/other ARM archs.  This comment by Nathaniel is the key:

> Unless someone wants to do lots of abi compatibility testing across different arm distributions, I think the most viable way forward here would be to push forward with the idea of distro-specific wheel tags, so that people could upload e.g "raspbian wheels"?

Please ping piwheels.org. Unfortunately I'm out of capacity to handle that.

**Comment by wrobell** [comment]
Fair enough. Just would like to point out that for Raspberry Pi, you would need to build for `armv6` only (see the pypa/manylinux#84 itself). RPi is probably the most popular ARM platform running Python, so IMHO it is worth considering.
