### ISSUE TITLE
Using uvloop on Mac create a lot of CLOSE_WAIT

### ISSUE THREAD

**Issue by cwt** [MagicStack/uvloop#23]
I'm trying to use uvloop in my proxy project. The diff is below (or see it online [here](https://bitbucket.org/bashell-com/wormhole/branch/uvloop#diff)):
```diff
diff -r 4c40523b6830 -r 575a8ff4284f wormhole/proxy.py
--- a/wormhole/proxy.py	Fri May 06 14:41:45 2016 +0700
+++ b/wormhole/proxy.py	Tue May 10 09:44:00 2016 +0700
@@ -62,6 +62,12 @@
     if not (1 <= args.port <= 65535):
         parser.error('port must be 1-65535')
 
+    try:
+        import uvloop
+    except ImportError:
+        pass
+    else:
+        asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
     loop = asyncio.get_event_loop()
     try:
         loop.run_until_complete(
```
It work pretty fast for a while, then everything just stop. I stop process by control-c. `ps` show no process running. However, `netstat -an` show a lot of `CLOSE_WAIT` connections, and then I have to reboot my Mac to clear them.

Do I did something wrong in my code? It never happened when I use pure asyncio.

**Comment by 1st1** [comment]
Let me take a look. What should I do to reproduce this on my machine?

**Comment by cwt** [comment]
you can install it using this command:
`pip install https://bitbucket.org/bashell-com/wormhole/get/uvloop.tar.gz`

and then just run `wormhole`, it will open port 8800, then set your browser/system http_proxy to 127.0.0.1:8800 and try to load http (not https) site with a lot of pictures for a while (control-R or command-R works too).

**Comment by 1st1** [comment]
Right, that's what I'm doing... Can you send me the exact website on which everything stops working at some point? So far I've tried refreshing arstechnica & theverge (which have a ton of images/resources) for a while, everything works...

**Comment by 1st1** [comment]
I'm using Firefox for the test.

**Comment by cwt** [comment]
me too, I test on this site http://www.obec.go.th but the site is located in Thailand, may slow on your side.

**Comment by 1st1** [comment]
Hm, can't reproduce this. How many times do you refresh the frontpage of http://www.obec.go.th before it stops working?  Also, what version of uvloop are you using?

**Comment by cwt** [comment]
I use the latest one. just install it 1 hour ago.
I can't remember how many times I refresh the page. will try again, but now I already got this while the proxy is still running.

[screen shot](http://picpaste.com/Screen_Shot_2559-05-10_at_10.20.31-uYOxc0Tn.png)

**Comment by 1st1** [comment]
When this happens, can you close the browser, wait a few minutes, and then open it again? Sometimes TCP connections are closing very slowly, and in this case, system may run out of available sockets.

**Comment by 1st1** [comment]
Alright, I think I've reproduced the problem, however, I can see it for asyncio without uvloop too.

What's the output of `ulimit -n` on your machine?

Could you please do the following:

1. type `$ ulimit -n 128`
2. type `$ ulimit -n` -- should output `128`
3. then launch the `wormhole`
4. open three tabs in Firefox (I did arstechnica.com, news.ycombinator.com, theverge.com), load the pages and then start refreshing each tab one by one without waiting till they load.

With the above steps I can get both asyncio and asyncio+uvloop to reject browser connections.

**Comment by cwt** [comment]
Yes, I think that's the problem. My `ulimit -n` said 256, but the `MAX_TASKS` on my `server.py` is set to 1000. That should overload the system.

I think the problem is on my side now. Thank you for your help. I will close the issue.

**Comment by 1st1** [comment]
@cwt Sure, please reopen the issue if you find that uvloop behaves differently from asyncio.

BTW, have you seen any speed improvements with uvloop?

**Comment by cwt** [comment]
speed is really amazing! that also accelerate my problem on resource usage to happened faster than asyncio. with uvloop, hundreds of concurrent connections were created fast until number of sockets exceed the limit. now I already fix it by set semaphore limit to the 90% of max open files.

**Comment by 1st1** [comment]
Great to hear that!
