### ISSUE TITLE
Provide wheels

### ISSUE THREAD

**Issue by Tinche** [MagicStack/uvloop#24]
Consider providing wheels for all the major platforms. They install much more quickly and do no require your users to have a C toolchain and development libs installed.

**Comment by 1st1** [comment]
Good idea!

**Comment by 1st1** [comment]
I updated my release script to upload wheel for Mac OS X. There are no wheel packages for Linux, unfortunately, and Windows isn't yet supported.

**Comment by Tinche** [comment]
There are wheels for Linux. :)

https://github.com/pypa/manylinux

**Comment by methane** [comment]
I'm trying.  But travis's Linux machine (not container based) doesn't start for a long time...
https://travis-ci.org/methane/uvloop/builds/130526994
https://github.com/methane/uvloop/commit/1dac4c7e051b99f39fe0dfc02cacf8c159e84dbc

**Comment by 1st1** [comment]
> There are wheels for Linux. :)

Wow, I couldn't google that, thanks!

@saghul Do you think it's a good idea to provide Linux wheels compiled on CentOS 5? That's a pretty old Linux kernel, won't libuv be slower or less stable?

**Comment by saghul** [comment]
On linux we do most of the syscalls manually, so as long as you have a recent kernel we'll use the new stuff.

**Comment by 1st1** [comment]
So now we have manylinux & macOS wheels. Closing the issue.

**Comment by Tinche** [comment]
Sweet, great job!
