### ISSUE TITLE
uvloop on alpine-linux  install  error ?

### ISSUE THREAD

**Issue by hightfly** [MagicStack/uvloop#247]
Step 7/18 : RUN pip3 install uvloop -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
 ---> Running in 6ea056acafd5
Looking in indexes: http://pypi.douban.com/simple
Collecting uvloop
  Downloading http://pypi.doubanio.com/packages/75/99/7a470e4950d8ecb1b561e8483716c414cd51b8ee193de8eb23506275f5a7/uvloop-0.12.2.tar.gz (1.9MB)
Building wheels for collected packages: uvloop
  Building wheel for uvloop (setup.py): started
  Building wheel for uvloop (setup.py): finished with status 'error'
  Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-b3vzy1by/uvloop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-wa4vhtic --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/__init__.py -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/_patch.py -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/_testbase.py -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/_noop.py -> build/lib.linux-x86_64-3.6/uvloop
  running egg_info
  writing uvloop.egg-info/PKG-INFO
  writing dependency_links to uvloop.egg-info/dependency_links.txt
  writing top-level names to uvloop.egg-info/top_level.txt
  reading manifest file 'uvloop.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*' found under directory 'vendor/libuv/.git'
  warning: no previously-included files matching '*' found under directory 'vendor/libuv/docs'
  warning: no previously-included files matching '*' found under directory 'vendor/libuv/img'
  writing manifest file 'uvloop.egg-info/SOURCES.txt'
  copying uvloop/cbhandles.pxd -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/cbhandles.pyx -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/dns.pyx -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/errors.pyx -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/loop.c -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/loop.pxd -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/loop.pyx -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/pseudosock.pyx -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/request.pxd -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/request.pyx -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/server.pxd -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/server.pyx -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/sslproto.pxd -> build/lib.linux-x86_64-3.6/uvloop
  copying uvloop/sslproto.pyx -> build/lib.linux-x86_64-3.6/uvloop
  creating build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/async_.pxd -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/async_.pyx -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/basetransport.pxd -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/basetransport.pyx -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/check.pxd -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/check.pyx -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/handle.pxd -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/handle.pyx -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/idle.pxd -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/idle.pyx -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/pipe.pxd -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/pipe.pyx -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/poll.pxd -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/poll.pyx -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/process.pxd -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/process.pyx -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/stream.pxd -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/stream.pyx -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/streamserver.pxd -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/streamserver.pyx -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/tcp.pxd -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/tcp.pyx -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/timer.pxd -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/timer.pyx -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/udp.pxd -> build/lib.linux-x86_64-3.6/uvloop/handles
  copying uvloop/handles/udp.pyx -> build/lib.linux-x86_64-3.6/uvloop/handles
  creating build/lib.linux-x86_64-3.6/uvloop/includes
  copying uvloop/includes/__init__.py -> build/lib.linux-x86_64-3.6/uvloop/includes
  copying uvloop/includes/compat.h -> build/lib.linux-x86_64-3.6/uvloop/includes
  copying uvloop/includes/consts.pxi -> build/lib.linux-x86_64-3.6/uvloop/includes
  copying uvloop/includes/debug.h -> build/lib.linux-x86_64-3.6/uvloop/includes
  copying uvloop/includes/debug.pxd -> build/lib.linux-x86_64-3.6/uvloop/includes
  copying uvloop/includes/flowcontrol.pxd -> build/lib.linux-x86_64-3.6/uvloop/includes
  copying uvloop/includes/python.pxd -> build/lib.linux-x86_64-3.6/uvloop/includes
  copying uvloop/includes/stdlib.pxi -> build/lib.linux-x86_64-3.6/uvloop/includes
  copying uvloop/includes/system.pxd -> build/lib.linux-x86_64-3.6/uvloop/includes
  copying uvloop/includes/uv.pxd -> build/lib.linux-x86_64-3.6/uvloop/includes
  running build_ext
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... ./install-sh -c -d
  checking for gawk... no
  checking for mawk... no
  checking for nawk... no
  checking for awk... awk
  checking whether make sets $(MAKE)... no
  checking whether make supports nested variables... no
  checking build system type... x86_64-unknown-linux-gnu
  checking host system type... x86_64-unknown-linux-gnu
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether gcc understands -c and -o together... yes
  checking for style of include used by make... none
  checking dependency style of gcc... none
  checking if gcc supports -pedantic flag... yes
  checking for gcc way to treat warnings as errors... -Werror
  checking if gcc supports -fvisibility=hidden... yes
  checking if gcc supports -g flag... yes
  checking if gcc supports -std=gnu89 flag... yes
  checking if gcc supports -Wall flag... yes
  checking if gcc supports -Wextra flag... yes
  checking if gcc supports -Wno-unused-parameter flag... yes
  checking if gcc supports -Wstrict-prototypes flag... yes
  checking for ar... ar
  checking the archiver (ar) interface... ar
  checking how to print strings... printf
  checking for a sed that does not truncate output... /bin/sed
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking for fgrep... /bin/grep -F
  checking for ld used by gcc... /usr/x86_64-alpine-linux-musl/bin/ld
  checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 98304
  checking whether the shell understands some XSI constructs... yes
  checking whether the shell understands "+="... no
  checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
  checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
  checking for /usr/x86_64-alpine-linux-musl/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for dlltool... no
  checking how to associate runtime and link libraries... printf %s\n
  checking for archiver @FILE support... @
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking for sysroot... no
  ./configure: ./configure.lineno: line 1: /usr/bin/file: not found
  checking for mt... no
  checking if : is a manifest tool... no
  checking how to run the C preprocessor... gcc -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... yes
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/usr/x86_64-alpine-linux-musl/bin/ld) supports shared libraries... yes
  checking whether -lc should be explicitly linked in... no
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... yes
  checking whether make supports nested variables... (cached) no
  checking for dlopen in -ldl... yes
  checking for kstat_lookup in -lkstat... no
  checking for gethostbyname in -lnsl... no
  checking for perfstat_cpu in -lperfstat... no
  checking for pthread_mutex_init in -lpthread... yes
  checking for clock_gettime in -lrt... yes
  checking for sendfile in -lsendfile... no
  checking for socket in -lsocket... no
  checking for special C compiler options needed for large files... no
  checking for _FILE_OFFSET_BITS value needed for large files... no
  checking sys/ahafs_evProds.h usability... no
  checking sys/ahafs_evProds.h presence... no
  checking for sys/ahafs_evProds.h... no
  checking that generated files are newer than configure... done
  configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating libuv.pc
  config.status: executing depfiles commands
  config.status: executing libtool commands
  error: [Errno 2] No such file or directory: 'make': 'make'
  
  ----------------------------------------
  Failed building wheel for uvloop
  Running setup.py clean for uvloop
Failed to build uvloop
Installing collected packages: uvloop
  Running setup.py install for uvloop: started
    Running setup.py install for uvloop: finished with status 'error'
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-b3vzy1by/uvloop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-doft0_ll/install-record.txt --single-version-externally-managed --compile:

**Comment by jh3** [comment]
Same issue. No luck here yet.

**Comment by elprans** [comment]
You need all build prerequisites installed in order to build on platforms where prebuilt wheels are not available. In this case you ate missing GNU make. A C compiler and Python headers are also required

**Comment by hightfly** [comment]
> required

I already install need libraries on alpine linux . 

`RUN apk add --update --no-cache libpq postgresql-dev gcc g++ python3-dev musl-dev libffi-dev tzdata jpeg-dev zlib-dev libxml2-dev libxslt-dev`

What dependency libraries do I need to install?

**Comment by jlaine** [comment]
`No such file or directory: 'make': 'make'`

Do you have GNU make installed?

**Comment by hightfly** [comment]
> `No such file or directory: 'make': 'make'`
> 
> Do you have GNU make installed?

already solve

`RUN apk add --update --no-cache make  libpq postgresql-dev gcc g++ python3-dev musl-dev libffi-dev tzdata jpeg-dev zlib-dev libxml2-dev libxslt-dev`

**Comment by jlaine** [comment]
> already solve

OK, I'm closing this issue, feel free to re-open if I misunderstood.

**Comment by forana** [comment]
For anyone else arriving here on a fruitless google search: alpine 3.14 [requires a minimum of docker version 20.10.0](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0). I had been building on `python:3.8-alpine`, which was previously an alias of `python:3.8-alpine3.13` and is now an alias of `python:3.8-alpine3.14`, and suddenly getting cryptic errors very similar to the above. `apt install --upgrade docker-ce docker-ce-cli` (on the host, not in the container) fixed this issue for me.

Strangely, `uvloop` was the only build affected by this.

**Comment by ilons** [comment]
> For anyone else arriving here on a fruitless google search: alpine 3.14 [requires a minimum of docker version 20.10.0](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0). I had been building on `python:3.8-alpine`, which was previously an alias of `python:3.8-alpine3.13` and is now an alias of `python:3.8-alpine3.14`, and suddenly getting cryptic errors very similar to the above. `apt install --upgrade docker-ce docker-ce-cli` (on the host, not in the container) fixed this issue for me.
> 
> Strangely, `uvloop` was the only build affected by this.

@forana Brilliant! Thanks for the note!
