### ISSUE TITLE
uvloop closes server socket unexpectedly

### ISSUE THREAD

**Issue by th3mis** [MagicStack/uvloop#261]
Hello, I've faced with problem I created Unix server, then read yml, next after event loop executes, server socket is closed. Using default asyncio event loop everything is okay. What's wrong here?

* **uvloop version**: uvloop (0.12.2)
* **pyaml version**: pyaml (19.4.1)
* **Python version**: Python 3.6.8
* **Platform**: Ubuntu 18.04 x86-64

Code for reproduce:
```python
#!/usr/bin/env python3

import asyncio
import uvloop
import yaml


async def handler(r, w):
    print('handler', r, w, flush=True)


async def start():
    print('server created', flush=True)
    x = await asyncio.start_unix_server(handler, '/tmp/test.sock')
    print(x, x.sockets)


async def main():
    print('main')

    await start()
    await asyncio.sleep(3)

    print('read yaml')
    fh = open('/tmp/test.yml')
    x = yaml.load(fh, Loader=yaml.SafeLoader)
    fh.close()

    while True:
        await asyncio.sleep(0.5)
        print('busy loop')


asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Part of strace:
```
read(13, "", 8192)                      = 0
read(13, "", 8192)                      = 0
getsockname(11, {sa_family=AF_UNIX, sun_path="/tmp/test.sock"}, [110->17]) = 0
getpeername(11, 0x7ffcbe646d20, [110])  = -1 ENOTCONN (Transport endpoint is not connected)
close(11)                               = 0
epoll_ctl(3, EPOLL_CTL_DEL, 11, 0x7ffcbe647200) = -1 EBADF (Bad file descriptor)
close(11)                               = -1 EBADF (Bad file descriptor)
```

Here fd=11 is server socket. Which is closed when we run `await asyncio.sleep(0.5)`

**Comment by 1st1** [comment]
The `x` in `x = await asyncio.start_unix_server(handler, '/tmp/test.sock')` is a reference to a `Server` object that controls the uvloop's Unix server.  Because you don't do anything with it and have no hard reference to it after the `start()` coroutine completes, it gets garbage collected.

**Comment by th3mis** [comment]
> The `x` in `x = await asyncio.start_unix_server(handler, '/tmp/test.sock')` is a reference to a `Server` object that controls the uvloop's Unix server. Because you don't do anything with it and have no hard reference to it after the `start()` coroutine completes, it gets garbage collected.

So why there is no problem with default event loop? And how is correct way to use `start_unix_server` with uvloop?

**Comment by 1st1** [comment]
> So why there is no problem with default event loop?

There might be a circular reference in vanilla asyncio, which is a bug.

> And how is correct way to use start_unix_server with uvloop?

Use a context manager, as shown here: https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.Server

**Comment by th3mis** [comment]
> > So why there is no problem with default event loop?
> 
> There might be a circular reference in vanilla asyncio, which is a bug.
> 
> > And how is correct way to use start_unix_server with uvloop?
> 
> Use a context manager, as shown here: https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.Server

Thanks you! So, it's strange, there is no normal documentation for start_unix_server...

**Comment by 1st1** [comment]
Would really appreciate a PR to github/python to improve it!
