### ISSUE TITLE
[version 0.13.0] Missed wheels with manylinux1 

### ISSUE THREAD

**Issue by sirkonst** [MagicStack/uvloop#265]
* **uvloop version**: 0.13.0
* **Python version**: 3.7
* **Platform**: linux

Why for version 0.13.0 is not attached whls files for `manylinux1`?

**Comment by 1st1** [comment]
Why do you need them?  IIRC we had a problem with compiling recent versions of libuv with manylinux1.

**Comment by sirkonst** [comment]
I have a problem on my environment. For install the version 0.13 compiling is required now. I don't know why, just a sadness fact. But 0.12 installs from precompiled wheel (manylinux1).

**Comment by jlaine** [comment]
Have you tried updating your pip using `pip install -U pip`? I was also surprised that I was not using precompiled wheels on Debian/buster until I updated pip.

**Comment by brunobord** [comment]
I'd like to report the same issue here. Please read below:

```
pip install uvloop==0.13.0 --only-binary=:all:
Collecting uvloop==0.13.0
  Could not find a version that satisfies the requirement uvloop==0.13.0 (from versions: 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0rc1, 0.12.0, 0.12.1, 0.12.2)
No matching distribution found for uvloop==0.13.0
```

compared to:

```
pip install uvloop==0.13.0
Collecting uvloop==0.13.0
  Using cached https://files.pythonhosted.org/packages/e3/15/dc3276384f4363015d7c72282f37066bae26c77f99158f66c9058ac167cf/uvloop-0.13.0.tar.gz
```

That might become a problem when you're deploying on an environment where, for security reasons, you must not have a C compiler installed.
*Ergo*, you can't install the latest uvloop version.

A strange fact, though, I can *see* the wheels on PyPI: https://pypi.org/project/uvloop/#files
Would it be possible that they were corrupted?

**Comment by elprans** [comment]
@brunobord The 0.13.0 wheels use the manylinux_2010 profile, which require pip 10.x or later to be recognized.

**Comment by brunobord** [comment]
my pip version is:

```
$ pip --version
pip 18.1 from /home/bbord/venv/lib/python3.7/site-packages/pip (python 3.7)
```

When trying to install the package again, it fails to find the .whl.
Time to fix this, indeed.

**Comment by elprans** [comment]
Work for me on pip-19.2.3:

```
$ pip install uvloop==0.13.0 --only-binary=:all:
Collecting uvloop==0.13.0
  Using cached https://files.pythonhosted.org/packages/bb/27/83c42973ae0a27340c32170fa261f1692319371df1fb3bf054a00dd52d7c/uvloop-0.13.0-cp37-cp37m-manylinux2010_x86_64.whl
Installing collected packages: uvloop
Successfully installed uvloop-0.13.0
```

Please try updating `pip` to the latest version.

**Comment by brunobord** [comment]
indeed it worked with pip==19.2.3, thx.

**Comment by jlaine** [comment]
@sirkonst could you report back whether updating pip also fixes the issue for you?

**Comment by sirkonst** [comment]
Sorry, you absolutely right updating a PIP resolves a problem.
