### ISSUE TITLE
RuntimeError: cannot convert sockaddr into Python object

### ISSUE THREAD

**Issue by mosquito** [MagicStack/uvloop#269]
* **uvloop**: 0.13.0
* **Python **: Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
* **Platform**: MacOS
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: yes

After installing `uvloop` as an event-loop factory my UDP server implementation stops working.

```
Unhandled exception in event loop
Traceback (most recent call last):
  File "uvloop/handles/udp.pyx", line 335, in uvloop.loop.__uv_udp_on_receive
  File "uvloop/dns.pyx", line 63, in uvloop.loop.__convert_sockaddr_to_pyaddr
RuntimeError: cannot convert sockaddr into Python object
```

That's because [__convert_sockaddr_to_pyaddr](https://github.com/MagicStack/uvloop/blob/master/uvloop/dns.pyx#L25) not compatibles af_unix socket family I guess.

**Comment by 1st1** [comment]
Do you want to submit a patch?

**Comment by mosquito** [comment]
@1st1 #271 fixes my case. But I'm not sure about tests which I have to add. I actually have not investigated well enough your test cases.

**Comment by mosquito** [comment]
@1st1 if possible, I would leave it open until a new version has been released.

**Comment by 1st1** [comment]
I've just published https://github.com/MagicStack/uvloop/releases/tag/v0.14.0rc1.  Please test.  The final release will be published some time next week if RC1 is OK.
