### ISSUE TITLE
Blog post URL seems to be dead

### ISSUE THREAD

**Issue by saveshodhan** [MagicStack/uvloop#272]
* **uvloop version**: NA
* **Python version**: NA
* **Platform**: NA
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: NA

The [link](http://magic.io/blog/uvloop-blazing-fast-python-networking/) to the blog post mentioned in the readme seems to be dead. Gives the below message when loaded:
> Page Not Found
> Looks like you've followed a broken link or entered a URL that doesn't exist on this site.
> 
>  Back to our site

**Comment by Nothing4You** [comment]
Works for me

**Comment by 1st1** [comment]
Yeah, thanks for reporting this. Should be up now.
