### ISSUE TITLE
Connection reset error when using autobahn

### ISSUE THREAD

**Issue by maheshnayer** [MagicStack/uvloop#279]
* **uvloop version**: 0.12.0
* **Python version**: 3.7.2
* **Platform**: ubuntu 16.04
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**:

Stack trace:

019-10-19 00:07:57.801306+05:30 - ERROR - Exception in callback <bound method WebSocketAdapterProtocol.connection_lost of <main.ClientProtocol object at 0x7f9d7516eb38>>
handle:
Traceback (most recent call last):
File "uvloop/cbhandles.pyx", line 64, in uvloop.loop.Handle._run
File "/home/ubuntu/streamer/venv3/lib/python3.7/site-packages/autobahn/asyncio/websocket.py", line 100, in connection_lost
self._connectionLost(exc)
File "/home/ubuntu/streamer/venv3/lib/python3.7/site-packages/autobahn/websocket/protocol.py", line 3365, in _connectionLost
WebSocketProtocol._connectionLost(self, reason)
File "/home/ubuntu/streamer/venv3/lib/python3.7/site-packages/autobahn/websocket/protocol.py", line 1069, in _connectionLost
if not self.factory.isServer and self.serverConnectionDropTimeoutCall is not None:
AttributeError: 'ClientProtocol' object has no attribute 'serverConnectionDropTimeoutCall'
2019-10-19 00:07:57.801934+05:30 - ERROR - Task exception was never retrieved
future: <Task finished coro=<<iterable_coroutine without name>()> exception=ConnectionResetError()>
Traceback (most recent call last):
File "uvloop/loop.pyx", line 1945, in create_connection
File "uvloop/loop.pyx", line 1942, in uvloop.loop.Loop.create_connection
File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._on_handshake_complete
ConnectionResetError

Autobahn version - 19.1.1
Any help appreciated

**Comment by 1st1** [comment]
So what's the problem with this?  Does it happen all the time? Is this logged or does it bring down the server? It isn't clear from your submission what's happening and what we need to look at. Please provide us with more details.

**Comment by maheshnayer** [comment]
It doesn't bring down the server. It doesn't happen often though. Once or twice a day but it raises an exception that I'm unable to catch and handle accordingly and I'm unable to figure out the reason for this issue. I have a websocket client connected to a remote server. The connections are usually open for extended periods of time and a break in connection is handled accordingly except for this scenario

**Comment by 1st1** [comment]
Do they actually break? Are you just annoyed by seeing errors in the log, or are there actual connectivity issues?

The traceback you shared can be explained by clients disconnecting in the middle of establishing a connection. There's nothing wrong with it. Maybe we should just silence logs like that?

**Comment by fantix** [comment]
@maheshnayer are you using the [WAMP Application Component](https://github.com/crossbario/autobahn-python#wamp-application-component)? Searching the autobahn source code, it seems to be the only place calling `create_connection` unless your own code is trying to establish SSL/TLS connections.

As @1st1 explained, `ConnectionResetError` means your client dropped the connection before completing the SSL/TLS handshake, but your server code (autobahn or custom) is not handling the exception properly ("Task exception was never retrieved"). For example:

```python
import asyncio
import socket
import threading

import uvloop

asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())


def server():
    s = socket.socket()
    s.bind(('127.0.0.1', 8088))
    s.listen(1)
    while True:
        s.accept()[0].close()


threading.Thread(target=server, daemon=True).start()


def done(f):
    try:
        res = f.result()
        print('Result:', res)
    except Exception as e:
        print('Exception:', type(e), e)
    loop.stop()


# autobahn Component:
asyncio.ensure_future(
    asyncio.wait_for(asyncio.open_connection('127.0.0.1', 8088, ssl=True),
                     3600)).add_done_callback(done)

loop = asyncio.get_event_loop()
loop.run_forever()

print('=' * 80)

# without proper callback:
asyncio.ensure_future(
    asyncio.wait_for(asyncio.open_connection('127.0.0.1', 8088, ssl=True),
                     3600))

loop.run_until_complete(asyncio.sleep(1))
```

Outputs:

```
Exception: <class 'ConnectionResetError'> 
================================================================================
Task exception was never retrieved
future: <Task finished coro=<wait_for() done, defined at /3.7.0/lib/python3.7/asyncio/tasks.py:367> exception=ConnectionResetError()>
Traceback (most recent call last):
  File "/3.7.0/lib/python3.7/asyncio/tasks.py", line 412, in wait_for
    return fut.result()
  File "/3.7.0/lib/python3.7/asyncio/streams.py", line 77, in open_connection
    lambda: protocol, host, port, **kwds)
  File "uvloop/loop.pyx", line 1945, in create_connection
    raise
  File "uvloop/loop.pyx", line 1942, in uvloop.loop.Loop.create_connection
    await ssl_waiter
  File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._on_handshake_complete
    raise handshake_exc
ConnectionResetError

```

Before the line, the exception is properly handled; after the line, it simulates exactly your 2nd exception. For the first exception (`serverConnectionDropTimeoutCall` is not found) I think it might be the trigger, but I don't know the connection without seeing your actual code.

@1st1 if this is the case, there's nothing we can do in uvloop to silence this error - we have to raise the `ConnectionResetError` out.

**Comment by 1st1** [comment]
> @1st1 if this is the case, there's nothing we can do in uvloop to silence this error - we have to raise the ConnectionResetError out.

Yeah. FWIW this looks like a bug in autobahn.  Also `AttributeError: 'ClientProtocol' object has no attribute 'serverConnectionDropTimeoutCall'` looks very suspicious.

@maheshnayer is it only with uvloop you see these exceptions?

**Comment by fantix** [comment]
Another example using autobahn WebSocket client:

```python
import asyncio
import socket
import threading

from autobahn.asyncio.websocket import WebSocketClientFactory, WebSocketClientProtocol

import uvloop

uvloop.install()


class MyProtocol(WebSocketClientProtocol):
    def connection_lost(self, exc):
        pass
   

def server():
    s = socket.socket()
    s.bind(('127.0.0.1', 9000))
    s.listen(1)
    while True:
        s.accept()[0].close()


threading.Thread(target=server, daemon=True).start()

factory = WebSocketClientFactory(u"ws://127.0.0.1:9000")
factory.protocol = MyProtocol

loop = asyncio.get_event_loop()
coro = loop.create_connection(factory, '127.0.0.1', 9000, ssl=True)
try:
    loop.run_until_complete(coro)
except Exception as e:
    print(type(e))

print('=' * 80)
asyncio.ensure_future(loop.create_connection(factory, '127.0.0.1', 9000, ssl=True))
loop.run_until_complete(asyncio.sleep(1))
```

Same output:
```
<class 'ConnectionResetError'>
================================================================================
Task exception was never retrieved
future: <Task finished coro=<<iterable_coroutine without __name__>()> exception=ConnectionResetError()>
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1945, in create_connection
    raise
  File "uvloop/loop.pyx", line 1942, in uvloop.loop.Loop.create_connection
    await ssl_waiter
  File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._on_handshake_complete
    raise handshake_exc
ConnectionResetError
```

**Comment by fantix** [comment]
If you turn on asyncio debug, it will reveal the source of the problem:
```
$ PYTHONASYNCIODEBUG=1 python t.py 
<class 'ConnectionResetError'>
================================================================================
Task exception was never retrieved
future: <Task finished coro=<<iterable_coroutine without __name__>()> exception=ConnectionResetError() created at t.py:38>
source_traceback: Object created at (most recent call last):
  File "t.py", line 38, in <module>
    asyncio.ensure_future(loop.create_connection(factory, '127.0.0.1', 9000, ssl=True))
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1945, in create_connection
    raise
  File "uvloop/loop.pyx", line 1942, in uvloop.loop.Loop.create_connection
    await ssl_waiter
  File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._on_handshake_complete
    raise handshake_exc
ConnectionResetError
```

**Comment by 1st1** [comment]
@maheshnayer could you please file this bug to the autobahn bug tracker referencing this issue?

**Comment by maheshnayer** [comment]
I have raised an issue at auto bahn. Closing this for now. Thank you
