### ISSUE TITLE
UNIX socket is automatically unlinked

### ISSUE THREAD

**Issue by AndreLouisCaron** [MagicStack/uvloop#28]
When using the built-in event loop, you need to do something like this:

```
server = await asyncio.start_unix_server(client_connected, path=path)
try:
    # ...
finally:
    server.close()
    await server.wait_closed()
    os.unlink(path)
```

However, when I use uvloop, the `os.unlink()` call raises a `FileNotFoundError` exception.

I was wondering if you already know about this and if it is intentional?

I don't mind adding a try/except clause to silence the exception, but if you're aiming for this event loop to be a drop-in replacement for the built-in event loop, I guess you're going to want to change this?

**Comment by 1st1** [comment]
Hm, libuv unlinks the path unconditionally, I can't do anything about it.

@saghul, sorry for bothering you, do you think it's possible to add a flag in libuv to tell it not to unlink the path in `uv__pipe_close`?

**Comment by 1st1** [comment]
Alternatively we can re-create the `path` once the unix socket is closed, but it feels too hacky to me.

**Comment by saghul** [comment]
No worries Yuri. I don't think we'd do that. See the comment before the unlink, it prevents a race.

Alternatively, you can create a UNIX socket with the Python socket module and use uv_pipe_open, that way the path won't be unlinked because libuv doesn't store it.

**Comment by 1st1** [comment]
@saghul Good idea, I followed your advice :)

@AndreLouisCaron Thanks for reporting this! Should be fixed in the `master` branch; I'll also issue a new uvloop release shortly.

**Comment by AndreLouisCaron** [comment]
Thanks!

**Comment by 1st1** [comment]
I've just released uvloop v0.4.26. Please check it out.

**Comment by AndreLouisCaron** [comment]
Just tried 0.4.26 and it now works as expected!  Thanks!

**Comment by 1st1** [comment]
Thanks! Closing the issue.
