### ISSUE TITLE
install fails in macOS Catalina 

### ISSUE THREAD

**Issue by arvibd** [MagicStack/uvloop#293]
* **uvloop version**:
* **Python version**:
* **Platform**:
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**:
* **Does uvloop behave differently from vanilla asyncio? How?**:

recreate the issue : 
`python3.8 -m pip install uvloop`
or 
`python3.8 -m pip install git+https://github.com/MagicStack/uvloop`

**Comment by e0en** [comment]
I guess that it is a duplicate of https://github.com/MagicStack/uvloop/issues/277

**Comment by arvibd** [comment]
> I guess that it is a duplicate of #277

No this one is related to the zsh being the default shell on macOS

**Comment by 1st1** [comment]
> No this one is related to the zsh being the default shell on macOS

Python 3.8 isn't yet supported. Can you try to install with 3.7?

In any case, I don't have Catalina yet and so I'd appreciate a PR with a fix if there's a bug.

**Comment by 1st1** [comment]
I've just published https://github.com/MagicStack/uvloop/releases/tag/v0.14.0rc1.  Please try it.  If it does not work, please share the output of `pip install --vebose uvloop`

**Comment by arvibd** [comment]
It's working
