### ISSUE TITLE
What if run `c`-code with python

### ISSUE THREAD

**Issue by alex-eri** [MagicStack/uvloop#300]
* **uvloop version**: 0.11.2
* **Python version**: 3.7
* **Platform**: linux-amd64
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**:
* **Does uvloop behave differently from vanilla asyncio? How?**:

I want run server on `libuv` written in `c`. And I want to run handler written in `python` on same loop.

How to start pythons uvloop non blocking c code?
Can i "await" pythons function non blocking ?

**Comment by 1st1** [comment]
There are no APIs to get a reference to the underlying libuv primitives or to schedule C functions (you need to wrap them in Python objects somehow).
