### ISSUE TITLE
Running Tornado with asyncio and uvloop

### ISSUE THREAD

**Issue by loretoparisi** [MagicStack/uvloop#301]
Hello I'm running Tornado with asyncio

```python
class WebServer(threading.Thread):
    def run(self):
        PORT = os.getenv('PORT', 8888)
        N_CPU = multiprocessing.cpu_count()
        #asyncio.set_event_loop(asyncio.new_event_loop())
        asyncio.set_event_loop_policy(AnyThreadEventLoopPolicy())
        asyncio.get_event_loop().set_default_executor(ThreadPoolExecutor(max_workers=N_CPU))
        app = application()
        app.listen(PORT)
        tornado.ioloop.IOLoop.instance().start()
WebServer().start()
```

I'm using `AnyThreadEventLoopPolicy` to avoid threading issues since I'm using both `@tornado.web.asynchronous`, `@tornado.gen.coroutine` and `@tornado.concurrent.run_on_executor()`.

If I run with `asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())` I will get an error:

```
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "tornadoaas.py", line 114, in run
    asyncio.get_event_loop().set_default_executor(ThreadPoolExecutor(max_workers=N_CPU))
  File "/usr/local/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.
```

How to integrate this approach with uvloop, hence keeping the `AnyThreadEventLoopPolicy`?

**Comment by 1st1** [comment]
https://github.com/MagicStack/uvloop/wiki

**Comment by loretoparisi** [comment]
@1st1 I have read the docs, that solution does not work in every cases: you are going to get a `RuntimeError: There is no current event loop in thread 'Thread-1'.` error if you use this init code:

```python
asyncio.set_event_loop_policy( uvloop.EventLoopPolicy() )
asyncio.get_event_loop().set_default_executor(ThreadPoolExecutor(max_workers=N_CPU))
app = application()
app.listen(PORT)
tornado.ioloop.IOLoop.instance().start()
```

**Comment by 1st1** [comment]
Try removing the set_default_executor line. Other than that I cannot help as I don't use tornado :( Try opening an issue at the tornado github issue tracker.

**Comment by loretoparisi** [comment]
@1st1 okay go without that, if it works the problem is that this specific line `asyncio.get_event_loop().set_default_executor(ThreadPoolExecutor(max_workers=N_CPU))
` was suggested by Tornado team to limit the number of running threads:
https://github.com/tornadoweb/tornado/issues/2762

**Comment by 1st1** [comment]
iirc they are already limited in recent asyncio/uvloop versions

**Comment by Integralist** [comment]
Here's a recent example that uses latest uvloop and tornado versions, I don't seem to need any of the stuff specified in the FAQ though? 

e.g. I'm just importing uvloop and calling `uvloop.install()` before setting up the tornado application.

So at this point I'm not sure if this is working or if it's just failing quietly 🤔 

I mean I can make a request to the server and it'll respond so I have to presume that if the uvloop integration isn't working then it's allow tornado to continue functioning without error...

```python
import os

import tornado.autoreload
import tornado.httpserver
import tornado.ioloop
import tornado.options
import tornado.web
import uvloop

app_settings = {
    "env": os.environ.get("ENV", "dev"),
    "port": os.environ.get("APP_PORT", "9000"),
}


class FooHandler(tornado.web.RequestHandler):
    async def get(self, *args, **kwargs):
        self.finish("foo")


class App(tornado.web.Application):
    def __init__(self):
        super().__init__([
            (r"/", FooHandler),
        ], **app_settings)


if __name__ == "__main__":
    uvloop.install()

    tornado.options.options.logging = None  # configure tornado to leave logging alone

    if app_settings["env"] == "dev":
        tornado.autoreload.start()
        App().listen(app_settings["port"])
    else:
        server = tornado.httpserver.HTTPServer(App())
        server.bind(app_settings["port"])
        server.start(0)  # multi process mode (one process per cpu)

    tornado.ioloop.IOLoop.current().start()
```

**Comment by thisisrandy** [comment]
> So at this point I'm not sure if this is working or if it's just failing quietly

@Integralist, I'm sure you've long since figured this out, but as I am coming to this now wondering the same thing, I thought I'd chime in that

```python
io_loop = tornado.ioloop.IOLoop.current()
isinstance(io_loop.asyncio_loop, uvloop.Loop) == isinstance(io_loop.selector_loop, uvloop.Loop) == True
```

which seems like good evidence that the installation is working to me.
