### ISSUE TITLE
this code runs in python3.6 but not in PyPy3.6 7.2 x86_64

### ISSUE THREAD

**Issue by schalekamp** [MagicStack/uvloop#303]
* **uvloop 0.14**:
* **Python 3.6**:
* **Platform Ubuntu 18.04**:
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**:
* **Does uvloop behave differently from vanilla asyncio? How?**:

loop = asyncio.get_event_loop()
task = asyncio.ensure_future(self._async_connect())
loop.run_until_complete(task)
logger.info('_async_connect completed')
authenticate()

This code works fine in python3.6, but when I try to run it using pypy I get the following error:

loop.run_until_complete(task)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
TypeError: object generator can't be used in 'await' expression

Any help to what is going on would be much appreciated.

**Comment by asvetlov** [comment]
Curious why do you want to use uvloop on pypy?

**Comment by schalekamp** [comment]
I'd like the fastest solution (latency) possible.
I'm guessing using uvloop and pypy would be that solution.
But I cannot test or prove it.

**Comment by schalekamp** [comment]
according to  [https://github.com/MagicStack/uvloop/issues/132](url) it's a pypy issue.
supposedly "pypy not supporting async generator syntax since it's still based on 3.5." 
if that's the case I wonder how I should rewrite my code so I could still run this?

**Comment by asvetlov** [comment]
uvloop is Cython based code that is translated into C Extension.
PyPy is proven to be super slow for C Extensions, they are usually much slower than python code executed on PyPy.

I very doubt if you can speed your code up in this way.
If you'll get different numbers please share it.

**Comment by schalekamp** [comment]
I naively thought accessing C extensions from Python would be as fast as accessing them from PyPy.
If that would be the case then PyPy would be the best of both worlds.
Why is accessing C extensions from PyPy superslow compared to Python?

**Comment by asvetlov** [comment]
I wonder are you banned by Google search engine?
If yes this is the link: https://morepypy.blogspot.com/2018/09/inside-cpyext-why-emulating-cpython-c.html

**Comment by schalekamp** [comment]
I naively thought you were a nice person. I guess I was wrong.
Thanks for posting the link though.
