### ISSUE TITLE
BUG: uvloop.loop.create_task() is missing 'name' parameter

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [MagicStack/uvloop#309]
compare:

1. `uvloop.loop.create_task()`
https://github.com/MagicStack/uvloop/blob/master/uvloop/loop.pyx#L1389

with:

2. `asyncio.loop.create_task()`
https://docs.python.org/3/library/asyncio-eventloop.html?#asyncio.loop.create_task

**Comment by 1st1** [comment]
Yeah, this is a bug.
