### ISSUE TITLE
Support preexec_fn argument in loop.subprocess_exec

### ISSUE THREAD

**Issue by 1st1** [MagicStack/uvloop#31]
Add support for `preexec_fn` in `loop.subprocess_exec` -- a callback that gets called in the forked process right before `exec`.

**Comment by 1st1** [comment]
@saghul this is the last thing in uvloop that isn't currently supported, and the only thing that has to be implemented in libuv. And this is something that people actually use, for instance Facebook guys use it to call `prctl(PR_SET_PDEATHSIG, SIGKILL)` in the child processes.

Essentially, I'm thinking if it's possible to add another field to `uv_process_options_t`: a pointer to a `(void)after_fork()` function.  Would that be possible?  I think I can make a PR.

**Comment by saghul** [comment]
@1st1 that would break the ABI so it would have to wait for v2 if it gets accepted. Feel free to open an issue to kickstart the discussion!

**Comment by 1st1** [comment]
After giving it more thought, I think I can use `pthread_atfork`... Should be easier than pushing new stuff to libuv.

**Comment by 1st1** [comment]
Implemented in b5b3b12dbba915f635b583c8b51c1f41ed219d9c
