### ISSUE TITLE
udp sendto not working

### ISSUE THREAD

**Issue by stalkerg** [MagicStack/uvloop#319]
* **uvloop version**: 0.14.0
* **Python version**: 3.7.6
* **Platform**: Linux
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: yes
* **Does uvloop behave differently from vanilla asyncio? How?**: not working

Hello. Currently, I am trying to work with aiosip project and it's working very well but unfortunately, it stops working after installing uvloop.   
It looks like sendto do nothing and without any error. I can't see any UDP packet on any device. 

Probably I should go deeply with gdb.

PS datagram endpoint created fine and without exceptions https://github.com/stalkerg/aiosip/blob/master/aiosip/peers.py#L316

**Comment by stalkerg** [comment]
with uvloop 0.13.0 I have next error:
```
  File "uvloop/loop.pyx", line 2980, in create_datagram_endpoint
  File "uvloop/handles/udp.pyx", line 86, in uvloop.loop.UDPTransport._connect
OSError: [Errno 106] Transport endpoint is already connected
```

in same time with classic eventloop I have no any problems.

**Comment by stalkerg** [comment]
ok, with version 0.12.2 everything working fine.

**Comment by stalkerg** [comment]
after bisect I found this commit https://github.com/MagicStack/uvloop/commit/c2b65bc8d2e1bb759a755adb255f095fb40ce953 it's break UDP for aiosip (and I think not only).

**Comment by 1st1** [comment]
Thanks for reporting this. Could you please write a functional test that would exhibit the bug?

**Comment by stalkerg** [comment]
@1st1 yes, please
```python
import asyncio
import uvloop

uvloop.install()


class UDP(asyncio.DatagramProtocol):
    def __init__(self):
        pass

    def connection_lost(self, error):
        print("connection_lost", error)


async def main():
    loop = asyncio.get_event_loop()
    transport, proto = await loop.create_datagram_endpoint(
        lambda: UDP(),
        local_addr=("192.168.1.9", 6001),
        remote_addr=("192.168.1.3", 5060)
    )
    print("Before sending the message without a destination")
    transport.sendto(b"deadbeef")
    await asyncio.sleep(1)
    print("After sending the message without a destination")
    
    print("Before sending the message with a destination")
    transport.sendto(b"deadbeef", ("192.168.1.3", 5060)) # will be connection lost
    await asyncio.sleep(1)
    print("After sending the message with a destination")


asyncio.get_event_loop().run_until_complete(main())
```

looks like it happens if you trying to send a message with destination address and you have already specify it in create_datagram_endpoint as remote_addr.

**Comment by jlaine** [comment]
You cannot both bind the endpoint to a remote address and use `sendto()` with a destination address.

This is the case in vanilla asyncio too:

https://github.com/python/cpython/blob/85cf1d514b84dc9a4bcb40e20a12e1d82ff19f20/Lib/asyncio/selector_events.py#L1028
