### ISSUE TITLE
Add slow_callback_duration property to uvloop

### ISSUE THREAD

**Issue by jettify** [MagicStack/uvloop#33]
`asyncio` event loop has useful property `BaseEventLoop.slow_callback_duration` for logging long blocking operations [1]. It is not most critical feature but nice to have it during development.

[1] https://docs.python.org/3.5/library/asyncio-dev.html#debug-mode-of-asyncio

**Comment by 1st1** [comment]
Should be fixed in `v0.4.32`. Please check.

**Comment by 1st1** [comment]
Closing this one.
