### ISSUE TITLE
It's still faster than asyncio event loop?

### ISSUE THREAD

**Issue by spumer** [MagicStack/uvloop#339]
Now Python have event loop written in C. How much uvloop faster asyncio event loop in Py3.7 and Py3.8?

**Comment by 1st1** [comment]
Python does not have an event loop written in C.

**Comment by spumer** [comment]
Yea, you are right. It's just rewritten common objects on C, like Future :)

https://github.com/python/cpython/blob/master/Modules/_asynciomodule.c

**Comment by 1st1** [comment]
Yeah, I know, I did that :)

**Comment by pembeci** [comment]
This normally happens on Twitter. :)
