### ISSUE TITLE
Build error, open CFI at the end of file; missing .cfi_endproc directive

### ISSUE THREAD

**Issue by Nalorokk** [MagicStack/uvloop#340]
* **uvloop version**: 0.14.0
* **Python version**: 3.8.2
* **Platform**: aarch64
* **Can you reproduce the bug with PYTHONASYNCIODEBUG in env?**: Not related
* **Does uvloop behave differently from vanilla asyncio? How?**: Build error

    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -fno-semantic-interposition -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -march=armv8-a -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.8 -I/tmp/pip-install-psjdd3hx/uvloop/vendor/libuv/include -c uvloop/loop.c -o build/temp.linux-aarch64-3.8/uvloop/loop.o -O2
    {standard input}: Assembler messages:
    {standard input}:1017953: Warning: end of file not at end of a line; newline inserted
    {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
    gcc: fatal error: Killed signal terminated program cc1
    compilation terminated.
    error: command 'gcc' failed with exit status 1

**Comment by PeterJCLaw** [comment]
Hrm, according to https://stackoverflow.com/a/25584112, it looks like this might be an out of memory condition during the build?

**Comment by fantix** [comment]
Closing as "can't repro", please feel free to reopen if issue persists.

**Comment by aliforouzan** [comment]
As @PeterJCLaw  said It seems you haven't enough memory
