### ISSUE TITLE
Implement shutdown_default_executor()

### ISSUE THREAD

**Issue by agronholm** [MagicStack/uvloop#349]
* **uvloop version**: 0.14.0
* **Python version**: 3.9.0b1
* **Platform**: Linux
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: yes
* **Does uvloop behave differently from vanilla asyncio? How?**: yes – vanilla asyncio implements this method

Python 3.9 added a new mandatory method to the `AbstractEventLoop` interface, named [shutdown_default_executor()](https://docs.python.org/3.9/library/asyncio-eventloop.html#asyncio.loop.shutdown_default_executor). This method is crucial for `asyncio.run()` to work. If it's absent, `asyncio.run()` will fail with a `NotImplementedError` when performing the shutdown cleanup.

Related CPython issue: https://bugs.python.org/issue34037

**Comment by aeros** [comment]
Seeing as I added `loop.shutdown_default_executor()` to asyncio, I wouldn't mind working on this issue. Unless someone else specifically wants to work on this, feel free to assign me and I should be able to find the time within the next couple of weeks or so.

(Note that this would be my first issue for uvloop)

**Comment by 1st1** [comment]
Kyle, feel free to work on this.

**Comment by aeros** [comment]
Sorry for the delay on this. I've been a bit otherwise occupied and had some local issues with installing cython in the virtual environment (due to an OS problem where `libffi.so.6` was not present). I just resolved the issue earlier today and should have time to open a PR for this issue within the next week or so.

**Comment by 1st1** [comment]
np!

**Comment by agronholm** [comment]
Really nice to have this. How soon can we expect a new uvloop release?

**Comment by 1st1** [comment]
I'll try to do one around 3.9 release. Sorry, i'm extremely busy these days.

**Comment by agronholm** [comment]
Python 3.9.0 has been released already so it would be really nice to get this done.

**Comment by pilosus** [comment]
It would be super nice to have this fix released! Can't wait to switch over Python 3.9.0 )

**Comment by hauntsaninja** [comment]
Thank you for uvloop! I'd love to see this released; if there's anything blocking I'm happy to help :-)

**Comment by 1st1** [comment]
I'm a bit busy with releasing EdgeDB b1. We should do that in a week or two and then it will be a priority for me to release uvloop (and migrate EdgeDB itself to 3.9).

**Comment by NotoriousRebel** [comment]
Any updates?

**Comment by agronholm** [comment]
EdgeDB b1 isn't out yet. I wouldn't expect anything to happen before that.
