### ISSUE TITLE
Any chance to get available on Windows?

### ISSUE THREAD

**Issue by spyderminer** [MagicStack/uvloop#352]
* **uvloop version**:uvloop-0.14.0.tar.gz
* **Python version**:3.7.3
* **Platform**:Windows 10
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: not a bug
* **Does uvloop behave differently from vanilla asyncio? How?**:

Request for Windows availability if possible. Thank you in advance!

Collecting uvloop
  Downloading https://files.pythonhosted.org/packages/84/2e/462e7a25b787d2b40cf6c9864a9e702f358349fc9cfb77e83c38acb73048/uvloop-0.14.0.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.0MB 8.5MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\********\AppData\Local\Temp\pip-install-p4v02jvp\uvloop\setup.py", line 15, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment

**Comment by 1st1** [comment]
https://github.com/MagicStack/uvloop/issues/14#issuecomment-575826367

**Comment by spyderminer** [comment]
I see. Thank you for your time!

**Comment by Vizonex** [comment]
See #736
