### ISSUE TITLE
python3.10 build issues due to deprocations in py3.10

### ISSUE THREAD

**Issue by L1ghtn1ng** [MagicStack/uvloop#356]
* **uvloop version**: latest pypi version
* **Python version**: 3.10
* **Platform**: linux

When uvloop tries to get built for python 3.10 it bombs out which you can see from the following

https://travis-ci.com/github/laramies/theHarvester/builds/177504632

**Comment by tacaswell** [comment]
I believe This can be fixed by re-cythonizing.

**Comment by Bennyelg** [comment]
+1

**Comment by jalelegenda** [comment]
> I believe This can be fixed by re-cythonizing.

Having the same problem. Can you expand on this, what does re-cythonizing mean? @tacaswell

**Comment by HacKanCuBa** [comment]
So, is this solved by 0.16.0? @L1ghtn1ng

**Comment by fantix** [comment]
As we're already building on 3.11, I'm closing this one now, but feel free to repoen if issue persists.
