### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [MagicStack/uvloop#367]
**Summary**
Installing uvloop on aarch64 via pip using command "pip3 install uvloop" tries to build wheel from source code.

**Problem description**
uvloop doesn't have wheel for aarch64 on PyPI repository. So, while installing uvloop via pip on aarch64, pip builds wheel for same resulting in it takes more time to install uvloop. Making wheel available for aarch64 will benefit aarch64 users by minimizing uvloop installation time.

**Expected Output**
Pip should be able to download uvloop wheel from PyPI repository rather than building it from source code.

@uvloop-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make uvloop wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by elprans** [comment]
Added in #376.  Please note that manylinux on aarch64 is [not stable yet](https://github.com/pypa/manylinux/issues/84), so consider aarch64 wheels to be beta.
