### ISSUE TITLE
pip install uvloop Issue in AWS ARM Graviton Chip

### ISSUE THREAD

**Issue by devidkarundeng** [MagicStack/uvloop#379]
* **uvloop version**: latest 0.14
* **Python version**: 3.8
* **Platform**: Ubuntu 20 + AWS's ARM Graviton Chip
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: -
* **Does uvloop behave differently from vanilla asyncio? How?**: -

Hi All,

I was tinkering with the new AWS Graviton ARM based chip last weekend, and while doing pip install uvloop, it gave error message "gcc.. arm64", so I figure might be the something to do with C compiler, and I installed base-library. 

`sudo apt base-library`

Looks like base-library solved other dependencies error in ARM64 graviton, but not uvloop.

After that, I tried another pip install uvloop, this time it is stuck at running building wheel for uvloop | , with the / (slash) spinning forever until the VPS instance crashed 💥 There is no error message, it's just stuck forever until crashing, so I do not have error message, sorry..

Any advise is much appreciated, Thanks!

**Comment by elprans** [comment]
Try the newly released 0.15.0.  There are experimental aarch64 wheels in that release.

**Comment by devidkarundeng** [comment]
Thanks @elprans! Tested today on aarch64: `pip install uvloop` was fetching 0.15 and successfully installed. Closing,
