### ISSUE TITLE
Exception [Errno 11] write could not complete without blocking

### ISSUE THREAD

**Issue by ale-dd** [MagicStack/uvloop#384]
Prompt_toolkit works flawlessly with asyncio but throws the exception in this issue's subject line when run via uvloop.

Some of the example programs in prompt_toolkit reproduce the issue:

https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1230

would anyone have some cycles to please take a look?

thank you!

**Comment by fantix** [comment]
I tried the two examples you mentioned in prompt-toolkit/python-prompt-toolkit#1230 and couldn't reproduce the same issue. Please try with the latest uvloop and feel free to reopen if the issue persists.
