### ISSUE TITLE
uvloop beta release

### ISSUE THREAD

**Issue by 1st1** [MagicStack/uvloop#4]
- [ ] Release alpha (see issue #3)
- [ ] Add support for UDP
- [ ] Support SSL in `loop.create_connection`, `loop.create_unix_connection`, `loop.create_server`, `loop.create_unix_server`

**Comment by GMLudo** [comment]
+10
I'll test that as soon as possible.
Ping @methane ;-)

**Comment by 1st1** [comment]
I decided to implement SSL and UDP in alpha. Closing this one. See issue #3 for updates.
