### ISSUE TITLE
uvloop blocks app and not executes aiohttp server

### ISSUE THREAD

**Issue by semakmillev** [MagicStack/uvloop#425]
Hi! I have very strange bug.
On server (only on the one - i cant reproduce error on others) i m tryin to start application using uvloop. Here is the code (i tried using docker, or executing script - result was the same) in console:

Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uvloop
>>> asyncio.set_event_loop_policy(uvloop.EventLoopPolicy()) # here i tried uvloop.install()
>>> from aiohttp import web
>>> app = web.Application()
>>> web.run_app(app, port=17000)

And after that nothing happens! Moreover, i can't stop process using Ctrl+C or Ctrl+D - only kill from other console

*i changed ports and got same results

uvloop version: 0.15.3
OS Version:
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"

**Comment by 1st1** [comment]
Sounds like the 17000 port is used by something else on that particular server. And most likely aiohttp has some timeout/retry logic in place and waits for it to become available. I don't think this is a uvloop bug. That said, check what happens if you don't activate uvloop -- does vanilla asyncio behave differently?

**Comment by semakmillev** [comment]
> Sounds like the 17000 port is used by something else on that particular server. And most likely aiohttp has some timeout/retry logic in place and waits for it to become available. I don't think this is a uvloop bug. That said, check what happens if you don't activate uvloop -- does vanilla asyncio behave differently?

1. As i mentioned - i used different ports - like 8023, 7091, 17091, 17000, 80 and several another with same result
2. Yes, if i run just
from aiohttp import web
app = web.Application()
web.run_app(app, port=17000)
everything works fine.

It's really strange. Seems to some hardware or system problem, because on other machine with same software i don't get this problem. But how to find out it - i dont know(

**Comment by bumer-t** [comment]
Hello. 
 
I have the same issue after upgrade libs:
aiohttp 3.6.2 --> 3.7.4.post0
uvloop 0.14.0 --> 0.16.0

I tested on different pythons: 3.6, 3.7, 3.9, but result was the same.
If I have only one pod - it was ok, but when I start 2nd pod -  pod doesn't listen 8080 port

My system:
`sh-4.2# cat /etc/*release :   CentOS Linux release 7.8.2003 (Core)`

If I run without `uvloop.install()` - it was ok.

**Comment by bumer-t** [comment]
I resolve this error with changed CentOS to Alpine (or Debian).
