### ISSUE TITLE
'uvloop.loop.TimerHandle' object has no attribute 'when'

### ISSUE THREAD

**Issue by YassineElbouchaibi** [MagicStack/uvloop#426]
* **uvloop version**: 0.15.3
* **Python version**: Python 3.8.6
* **Platform**: Not relevant
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: Not relevant
* **Does uvloop behave differently from vanilla asyncio? How?**: Yes

Asyncio's TimerHandle has a when method to get the scheduled callback time. See https://docs.python.org/3.8/library/asyncio-eventloop.html?highlight=timerhandle#asyncio.TimerHandle. This method was introduced in python 3.7.

uvloop doensn't define this this method and raises an exception on its usage. See https://github.com/MagicStack/uvloop/blob/c808a663b297bb2aee745523c277d6fafecebbeb/uvloop/cbhandles.pyx#L167-L309.

**Comment by 1st1** [comment]
Yeah, we should fix this. Care to submit a PR? :)

**Comment by YassineElbouchaibi** [comment]
Sure, however, I currently don't know how to get or calculate the exact value. I will have to have a look around first.

A naive solution would be to get the start time and add the delay to it but that would require getting the exact start time which I don't see how to do.

Like I said, I will have a look but if you have any suggestions, feel free to share as I´m not familiar with the what data is available.

**Comment by jensbjorgensen** [comment]
I submitted a pull request: https://github.com/MagicStack/uvloop/pull/428

**Comment by 1st1** [comment]
This is now part of 0.16.0!
