### ISSUE TITLE
'undable to perform send operation: no address'

### ISSUE THREAD

**Issue by deltaindiatango** [MagicStack/uvloop#44]
* uvloop 0.5
* python3.5.2
* Linux 4.4.0-1-amd64

Found a spelling error in an error message at https://github.com/MagicStack/uvloop/blob/master/uvloop/handles/udp.pyx#L218.

Thanks for the great work!

**Comment by 1st1** [comment]
Will be fixed in the next release (soon). BTW, are you using UDP with uvloop by any chance?

**Comment by deltaindiatango** [comment]
@1st1 Yes I am, I have a pretty minimal DNS resolver I'm running in uvloop.

**Comment by 1st1** [comment]
That's quite interesting, I'd love to check it out. Would be cool if it's open source.

**Comment by deltaindiatango** [comment]
@1st1 https://gist.github.com/deltaindiatango/7bf157202c17681d62667a006eb15abd

WIP but functional.
