### ISSUE TITLE
IPC support

### ISSUE THREAD

**Issue by sekkit** [MagicStack/uvloop#440]
Does it support IPC(interprocess communication) same as libuv?

**Comment by 1st1** [comment]
You can pass FDs to the spawned processes and named pipes, as well as communicate via stdin/stdout/stderr as asyncio API allows you to. You can also create TCP/UNIX sockets and implement IPC that way. There's nothing more that that to it.

See also https://docs.python.org/3/library/asyncio-subprocess.html#asyncio-subprocess
