### ISSUE TITLE
Build fails using CPython main.

### ISSUE THREAD

**Issue by ericsnowcurrently** [MagicStack/uvloop#450]
When I try to build uvloop (following the instructions in the README), it fails:

```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O0 -fPIC -I/home/esnow/projects/work/cpython-perf/uvloop/uvloop-dev-3.11/include -I/home/esnow/projects/work/cpython-perf/cpython/Include -I/home/esnow/projects/work/cpython-perf/cpython -c aiohttp/_websocket.c -o build/temp.linux-x86_64-3.11/aiohttp/_websocket.o
  aiohttp/_websocket.c:198:12: fatal error: longintrepr.h: No such file or directory
     #include "longintrepr.h"
              ^~~~~~~~~~~~~~~
```

I'm pretty sure this is a problem in Cython.  (I've opened https://github.com/cython/cython/issues/4461.)

**Comment by elprans** [comment]
Yea, it's a Python 3.11 incompatibility in Cython.  Fixed in cython/cython#4428 (unreleased yet).  Nothing we can do until Cython 0.29.25 is out.

**Comment by ericsnowcurrently** [comment]
Cool.  Thanks for the quick (and helpful) reply. 🙂

**Comment by Kludex** [comment]
This should not be closed yet.

A new Cython version was released since then, but I guess uvloop needs to build and release a new version.
