### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by mackeyja92** [MagicStack/uvloop#47]
Is UVLoop production ready? Getting ready to implement some new microservices on top of asyncio using UVLoop.

**Comment by 1st1** [comment]
I can only say that some top companies and startups are now using it in production. 

My advice would be to test uvloop, see if your services are stable on it, and then gradually replace asyncio event loop with it.

**Comment by mackeyja92** [comment]
Currently our stack is python 2 on twisted so we are moving some of our services out to py3 and asyncio.  But that is good enough for me! Thanks
