### ISSUE TITLE
Solaris 11 build fix

### ISSUE THREAD

**Issue by petriborg** [MagicStack/uvloop#48]
* **uvloop version**: 0.5.0 / master branch
* **python version**: python 3.5
* **platform**: Solaris 11

Build is successful on Solaris 11, but the uvloop.so file is missing references to kstat_* methods. To correct the issue the the gcc linker needs `-lkstat`

The below patch fixes the issue.

```
diff --git a/setup.py b/setup.py
index ba7bff2..e30783f 100644
--- a/setup.py
+++ b/setup.py
@@ -86,6 +86,8 @@ class libuv_build_ext(build_ext):
             self.compiler.add_library('rt')
         elif sys.platform.startswith('freebsd'):
             self.compiler.add_library('kvm')
+        elif sys.platform.startswith('sunos'):
+            self.compiler.add_library('kstat')

         super().build_extensions()
```

**Comment by kaniini** [comment]
:+1: patch works for me on a Solaris 11 box

**Comment by 1st1** [comment]
Care to make a PR? Or I can commit this myself referencing your name.

**Comment by petriborg** [comment]
Sure, created pull request #49.

**Comment by 1st1** [comment]
Closing the issue, the PR has been merged. Thank you!
