### ISSUE TITLE
Debug datatype bug: Tracked down to two potential triggers

### ISSUE THREAD

**Issue by ChristianCoenen** [MagicStack/uvloop#490]
* **uvloop version**:
* 0.16.0
* **Python version**:
* 3.10.2
* **Platform**:
* macOS - x86-64 based, reproduced on macOS - arm based
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**:
* Yes (although the error differs)
* **Does uvloop behave differently from vanilla asyncio? How?**:
The bug doesn't occur with vanilla asyncio.

The error is exactly the one described by Brett Brewer [here](https://youtrack.jetbrains.com/issue/PY-52654/TypeError-NoneType-object-is-not-callable-when-building-plots-with-the-debugger-using-Python-310#focus=Comments-27-5742502.0-0) (except that it also crashed for me when using "evaluate expression...").

Looking at the code snippet below, it can be seen that the error is related to an interplay between `uvloop`, `aiohttp` and `requests`. 

```python
import asyncio
import pdb

import aiohttp
import requests
import uvloop


async def make_requests() -> None:
    async with aiohttp.ClientSession() as session:
        await session.get("https://www.google.com")

    # Doesn't crash if one of the following conditions is True:
    # 1. The aiohttp call above is replaced with 'pass'
    # 2. The aiohttp call above uses 'http' instead of 'https'
    # 3. The requests call below uses 'http' instead of 'https'
    # 4. 'uvloop.install()' is commented
    requests.get("https://www.google.com")


def run() -> None:
    uvloop.install()
    asyncio.run(make_requests())


if __name__ == "__main__":
    pdb.run("run()")
```

## Important: 
**When building uvloop 0.16.0 locally (tested with python 3.10.2 and 3.10.0), this error does NOT occur => It seems like a problem with the CI pipeline or because python `3.10.0-rc.1` was used when uvloop 0.16.0 was built.**

**Comment by 1st1** [comment]
@fantix can you take a look?

**Comment by ChristianCoenen** [comment]
Update: The problem does not occur anymore in version 0.17.0.
