### ISSUE TITLE
FD duplication on transport.get_extra_info('socket') disables TCP_CORK and TCP_NODELAY for aiohttp

### ISSUE THREAD

**Issue by asvetlov** [MagicStack/uvloop#51]
Code work switching on cork/nodelay looks like this: https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/parsers.py#L243

It relies on `socket.setsockopt(...)` calls.

But uvloop returns another socket.
AFAIK socket flags are not shared between dups.
The problem is not such bad because libuv switches on nodelay by default IIRC but enabling/disabling CORK still makes sense.

**Comment by 1st1** [comment]
> But uvloop returns another socket.

Yes. This will be fixed once we fix asyncio to error when transport's socket is used with `loop.add_writer`

> AFAIK socket flags are not shared between dups.

TCP_NODELAY is shared (at least I observed that on Linux).  Could you please confirm that TCP_CORK isn't?

> The problem is not such bad because libuv switches on nodelay by default IIRC but enabling/disabling CORK still makes sense.

No, libuv doesn't set NODELAY by default (and uvloop does not either)...

**Comment by asvetlov** [comment]
Sorry, CORK is shared.
