### ISSUE TITLE
How to share libuv between multiple libraries

### ISSUE THREAD

**Issue by iceboy233** [MagicStack/uvloop#52]
If there are other C libraries using libuv and expose python interface, is there a way to use the same uv event loop for uvloop and the library?

**Comment by asvetlov** [comment]
To achieve it uvloop should only expose `uv_loop_t` instance, isn't it?

**Comment by 1st1** [comment]
What's the use case?

**Comment by iceboy-sjtu** [comment]
I'm playing with a HTTP server called [h2o](https://github.com/h2o/h2o) which supports to be used as a library and I'm trying to make a python binding for it (just for fun now - if it could be done, we can get a super high performance HTTP server). The server supports its own event loop and also uv loop. It'll be nice if we could make python bindings of these kind of libraries which share a single event loop.

**Comment by 1st1** [comment]
Interesting. Well, in theory we could provide some API for that, but somebody will have to pioneer and submit a PR with an example use case code.

**Comment by 1st1** [comment]
@iceb0y Are you still working on this?  I could probably expose a semi-public ctypes Ptr to the libuv event loop.

**Comment by ganwell** [comment]
Well, I'll need that too, I am writing a portable messaging library [chirp](https://github.com/concretecloud/chirp) connecting the major platforms (python, node, ruby... etc and C of course). The most efficient way to write bindings is uvloop and chirp sharing uv_loop_t. It shouldn't be too difficult to grab the pointer somewhere. It will take some time till I am writing the bindings... if there is no API for this till then, I'l do the PR.

**Comment by MarkReedZ** [comment]
I have a server that sets up uvloop in python then runs in C.  To access the loop I call out to python.  It would be nice to have access to the uv_loop_t to attach say this redis C client to the loop using the following code.

https://github.com/redis/hiredis/blob/master/adapters/libuv.h

Or if I have a PyObject * to the loop do I already have access?

cdef class Loop:
    cdef:
        uv.uv_loop_t *uvloop

**Comment by MarkReedZ** [comment]
Exposing the loop may not be a good idea as I believe I see uvloop and other libraries using the loop's data field.  It would at least need a note.  Locally I've exposed the loop by adding a function that returns it as a PyLong and am using it.

**Comment by fantix** [comment]
Fixed in #310
