### ISSUE TITLE
Pulsar in multiprocessing mode and Ctrl-C issue

### ISSUE THREAD

**Issue by lsbardel** [MagicStack/uvloop#54]
* **uvloop version**: 0.5.3
* **python version**: 3.5.2
* **platform**: Mac OS X 10.11.6

Hi, I'm testing uvloop integration with [pulsar](https://github.com/quantmind/pulsar) and it works a treat!
However, I have one problem when running in multiprocessing mode.

If I Ctrl-C on the shell, the master process receives the SIGINT signal but the subprocesses do not and do not respond to the master process sending QUIT signals either.
The subprocesses get eventually killed by pulsar master process using SIGKILL.
This only happen with uvloop.
Is there something I need to be aware about Ctrl-C with uvloop?

**Comment by 1st1** [comment]
No, uvloop should behave exactly as vanilla asyncio. Would it be possible for you to make a failing unittest similar to other subprocess tests in 'uvloop/tests/'?

**Comment by lsbardel** [comment]
I'm not sure how to do that! :disappointed:

The issue occurs only when I press Ctril-C on the shell.

If I send SIGINT/SIGTERM to the main process not using Ctrl-C, everything works as expected.
You can see it yourself by running this script:
```
pip install pulsar uvloop
py scripy.py --io uv
```
where ``script.py`` is
```python
from pulsar import MethodNotAllowed
from pulsar.apps import wsgi


def hello(environ, start_response):
    '''The WSGI_ application handler which returns an iterable
    over the "Hello World!" message.'''
    if environ['REQUEST_METHOD'] == 'GET':
        data = b'Hello World!\n'
        status = '200 OK'
        response_headers = [
            ('Content-type', 'text/plain'),
            ('Content-Length', str(len(data)))
        ]
        start_response(status, response_headers)
        return iter([data])
    else:
        raise MethodNotAllowed


def server(description=None, **kwargs):
    '''Create the :class:`.WSGIServer` running :func:`hello`.'''
    description = description or 'Pulsar Hello World Application'
    return wsgi.WSGIServer(hello, description=description, **kwargs)


if __name__ == '__main__':  # pragma nocover
    server().start()
```
Try to Ctrl-C and wait for about 5 seconds.
Than test with the vanilla asyncio loops
```
py script.py
```
or
```
py script.py --io select
```

**Comment by 1st1** [comment]
Alright, I'll take a look in a few days!

**Comment by 1st1** [comment]
I'm trying to figure out what's going on here and have some questions about how Pulsar works.  Could you please point out to the place where you fork/create subprocesses for actors?

**Comment by 1st1** [comment]
I see, it looks like you just instantiate `multiprocessing.Process` class.  In asyncio, it's more reliable to use `loop.subprocess_exec` for that (at least that's what `uvloop` is tuned for).

**Comment by lsbardel** [comment]
Right, that is what I suspected.
Pulsar was born before ``asyncio``, that is why ``multiprocessing`` module is used for process-based actors.
I will have to look into the ``subprocess_exec`` method and see what exactly does and compare with multiprocessing.

**Comment by lsbardel** [comment]
OK, using asyncio ``subprocess_exec`` fixes the issue.
Looks like the ``multiprocessing`` won't be used directly by pulsar anymore (I still need it for sharing server sockets between processes)

**Comment by 1st1** [comment]
Great! I ended up rewriting how signals handling is implemented in uvloop from scratch. Maybe multiprocessing will work just fine when I'm done.

**Comment by 1st1** [comment]
@lsbardel Please try uvloop 0.5.4. Ctrl-C is now being handled exactly as in asyncio.

**Comment by lsbardel** [comment]
Yes it works! Nice one.
Pulsar 1.5 will have two ways of doing multiprocessing, via asyncio subprocess or multiprocessing module. The asyncio way is better because it does not block during forking.
In any case thanks for feedback and fixes.

**Comment by 1st1** [comment]
@lsbardel Thanks for confirming that everything works now!  Closing this issue.
