### ISSUE TITLE
Can we update cython and make uvloop compatible with python 3.12 please?

### ISSUE THREAD

**Issue by tarsil** [MagicStack/uvloop#569]
* **uvloop version**: 0.17.0
* **Python version**: 3.12
* **Platform**: all
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: N/A
* **Does uvloop behave differently from vanilla asyncio? How?**: N/A

Cython was recently updated and this allows uvloop to be compatible with python 3.12. There are a plethora of projects out there that relies on this. 

Is it possible to prioritize this and make a release, please? Asyncpg, for instance, it's one of them. 

Appreciate the understanding,
tarsil

**Comment by robd003** [comment]
Here's the pull request to fix compatibility with 3.12 https://github.com/MagicStack/uvloop/pull/534

**Comment by AntonOfTheWoods** [comment]
There is absolutely no value in this issue over https://github.com/MagicStack/uvloop/issues/567. Please let the devs concentrate on upgrading, rather than creating unhelpful noise.
