### ISSUE TITLE
TypeError on Future declaration in Python 3.6.0b2 

### ISSUE THREAD

**Issue by mayfield** [MagicStack/uvloop#57]
- **uvloop version**: 89bf69f497c5eda4fac45656ad8d9a19c34e987f
- **python version**: Python 3.6.0b2 (default, Oct 12 2016, 20:13:22) (From docker python:3.6 (e6d7f066d57f))
- **platform**: Linux 4.7.6-200.fc24.x86_64

Trying out uvloop on the b2 build of python 3.6 fails to import..

```
Python 3.6.0b2 (default, Oct 12 2016, 20:13:22) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uvloop
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mayfield/project/uvloop/uvloop/__init__.py", line 7, in <module>
    from .loop import Loop as __BaseLoop, Future
  File "uvloop/future.pyx", line 249, in init uvloop.loop (uvloop/loop.c:114059)
    class Future(BaseFuture, aio_Future):
TypeError: multiple bases have instance lay-out conflict
```

**Comment by methane** [comment]
I'm sorry about incompatibilities at Python 3.6.
But inhertance from asyncio.future.Future is still required?

**Comment by 1st1** [comment]
@methane It's OK, that was expected. We can workaround the inheritance.  I already have a patch, but it segfaults python (I might have discovered a bug in Cython/Python 3.6, will need to check).

**Comment by 1st1** [comment]
uvloop 0.6.0 now runs on Python 3.6b3.
