### ISSUE TITLE
`__init__.pyi` added on #570 breaks mypy

### ISSUE THREAD

**Issue by vkottler** [MagicStack/uvloop#575]
* **uvloop version**: 0.18.0
* **Python version**: 3.11.4
* **Platform**: Linux (Ubuntu)
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: N/A
* **Does uvloop behave differently from vanilla asyncio? How?**: N/A

```
vkottler at vkottler-tower in ~/src/vkottler/vcorelib (dev/3.0.1)
$ ./venv/bin/mypy tests vcorelib setup.py tasks
vcorelib/asyncio/__init__.py:205: error: Module has no attribute "new_event_loop"  [attr-defined]
vcorelib/asyncio/__init__.py:209: error: Module has no attribute "install"  [attr-defined]
Found 2 errors in 1 file (checked 154 source files)
```

This appears to be caused by the addition of this file: https://github.com/MagicStack/uvloop/blob/master/uvloop/__init__.pyi.

It does not contain any information about e.g. `__all__` defined in [__init__.py](https://github.com/MagicStack/uvloop/blob/master/uvloop/__init__.py).

edit: [also reproduces in GitHub Actions](https://github.com/vkottler/vcorelib/actions/runs/6521029639/job/17709205753?pr=129)

**Comment by vkottler** [comment]
For my situation, I can just revert this commit: https://github.com/vkottler/vcorelib/commit/81a1ba3982c4abff3952e1b6f981d852d4ebb96e if/when there's a fix.

**Comment by fantix** [comment]
I believe #573 shall fix this issue.

**Comment by Kludex** [comment]
Is a release expected to happen soon?

**Comment by graingert** [comment]
@fantix can you cut a release with this fix in? it's blocking CI on uvicorn.

If you're busy that's ok just let me know and I'll depend on the git HEAD in uvicorn

**Comment by danking** [comment]
Thanks @fantix ! I think we can now close this issue.

https://github.com/MagicStack/uvloop/releases/tag/v0.19.0
