### ISSUE TITLE
possible signature mis-match with loop.create_server

### ISSUE THREAD

**Issue by xevrem** [MagicStack/uvloop#6]
in my project [paws](http://github.com/xevrem/paws) I use an uncommon usage of `loop.create_server` by [passing a pre-created reusable non-blocking socket](https://github.com/xevrem/paws/blob/master/paws/paws.py#L76) that may be causing an issue down the line with uvloop as shown in [this screenshot](http://imgur.com/mbs8UAJ).

I'm not 100% certain of this, but is this just an unhanded path or an incompatibility?

**Comment by 1st1** [comment]
Already fixed in v0.4.10!
