### ISSUE TITLE
move build logic to setup.py

### ISSUE THREAD

**Issue by p1otr** [MagicStack/uvloop#60]
Hi,

Could you move build logic from Makefile to setup.py? Like in asyncpg's 93733dba6c09673660614c014bae955dda9e8796?

TIA :)

**Comment by 1st1** [comment]
Yeah, that's planned. Why do you need that, btw?

**Comment by p1otr** [comment]
I plan to package it for Debian and even though it's only one additional line in my Makefile (debian/rules) - I'm lazy and I don't like hacks (anymore :)
The more people use it (and more will regenerate .c file if it's in setup.py) - the less work for me later... and you want more people to regenerate it, run tests, etc. f.e. to detect bugs like https://bugs.python.org/issue28634 early - thanks for the fix, BTW!
