### ISSUE TITLE
pulsar socket server in multiprocessing with uvloop

### ISSUE THREAD

**Issue by lsbardel** [MagicStack/uvloop#65]
* **uvloop version**: 0.6.7
* **python version**: 3.5.2 & 3.6.0
* **platform**: Mac OS x

When running pulsar in multiprocessing mode I get an error when using ``uvloop`` as the event loop.
To reproduce the error try the same code in issue #54 with pulsar from master branch:
```
pip install git+http://github.com/quantmind/pulsar.git@master#egg=pulsar uvloop
py scripy.py --io uv --concurrency multi -w 2
```
uvloop complains about the socket being not valid (closed probably).
```
11:24:10 [p=13310, t=140736205472704, ERROR, asyncio] Task exception was never retrieved
future: <Task finished coro=<SocketServer.worker_start() done, defined at /Users/lsbardel/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pulsar/apps/socket/__init__.py:270> exception=OSError(38, 'Socket operation on non-socket')>
Traceback (most recent call last):
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:105885)
  File "/Users/lsbardel/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pulsar/apps/socket/__init__.py", line 274, in worker_start
    server = await self.create_server(worker)
  File "/Users/lsbardel/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pulsar/apps/socket/__init__.py", line 323, in create_server
    await server.start_serving(cfg.backlog, sslcontext=self.sslcontext())
  File "/Users/lsbardel/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pulsar/async/protocols.py", line 666, in start_serving
    ssl=sslcontext)
  File "uvloop/loop.pyx", line 1376, in create_server (uvloop/loop.c:26228)
  File "uvloop/loop.pyx", line 1373, in uvloop.loop.Loop.create_server (uvloop/loop.c:26167)
  File "uvloop/handles/streamserver.pyx", line 43, in uvloop.loop.UVStreamServer.listen (uvloop/loop.c:72688)
  File "uvloop/handles/streamserver.pyx", line 80, in uvloop.loop.UVStreamServer._fatal_error (uvloop/loop.c:73173)
OSError: [Errno 38] Socket operation on non-socket
```
This occurs when using asyncio subprocess as process concurrency.
It looks like ``uvloop`` has closed the socket in the main process.

Pulsar create the socket server in the main process, than ``loop.remove_reader`` and pass the socket to subprocesses (implementation is https://github.com/quantmind/pulsar/blob/master/pulsar/apps/socket/__init__.py#L220 last five lines in the method).
This works with vanilla asyncio but it may not be the best way of doing it.

**Comment by 1st1** [comment]
I'll take a look in a few days.

**Comment by 1st1** [comment]
I see a different traceback now:

```
12:22:52 [p=17947, t=140736377529280, ERROR, asyncio] Task exception was never retrieved
future: <Task finished coro=<ActorSubProcess._start() done, defined at /Users/yury/dev/venvs/asyncio/lib/python3.5/site-packages/pulsar/async/concurrency.py:770> exception=OSError(9, 'Bad file descriptor')>
Traceback (most recent call last):
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:105907)
    result = meth(None)
  File "/Users/yury/dev/venvs/asyncio/lib/python3.5/site-packages/pulsar/async/concurrency.py", line 775, in _start
    'impl': bytes(ForkingPickler.dumps(self)),
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/reduction.py", line 235, in _reduce_socket
    df = DupFd(s.fileno())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/reduction.py", line 190, in DupFd
    return resource_sharer.DupFd(fd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/resource_sharer.py", line 48, in __init__
    new_fd = os.dup(fd)
OSError: [Errno 9] Bad file descriptor
```

I'm not sure I understand what's going on here. What socket are you working with?

**Comment by lsbardel** [comment]
**In the Master Process**
I create stream socket
```python
server = await loop.create_server(protocol, *address)
```
I get the sockets (usually two, ipv4 & v6) and remove their readers from the event loop
```python
sockets = server.sockets
for sock in sockets:
    loop.remove_reader(sock.fileno())
```
At this point I have the server sockets ready but not registered with the event loop.
At this point these sockets are passed to child processes using the multiprocessing socket serialization mechanism.

**In the Child Process**
The sockets are registered with the child process event loop

**Removing versus not removing**
Using this method I have several child processes serving the socket application but the master process is not serving.
This works with vanilla ``asyncio``, but with ``uvloop``, the serialisation fails with the error you see above (your error is a different version of the one I reported but they are caused by the same issue).
It looks like uvloop closes the sockets at some point after the `remove_reader` function call.

If **I dont' remove the reader** in the master process, everything works as expected. Which means the main process will serve the application as well as the workers.

**Comment by lsbardel** [comment]
As I mentioned above, if I don't remove the reader, multiprocessing socket servers work in pulsar.
That is what I'm doing now, therefore this ticket is not as important as I thought it was.
However, it would still be interesting to know why uvloop does not like my original implementation.

**Comment by 1st1** [comment]
> I get the sockets (usually two, ipv4 & v6) and remove their readers from the event loop

Oh, you shouldn't do that :( You are not supposed to use low-level `remove_reader` API on underlying sockets of any transports or servers. This already triggers an error (for most cases) in asyncio and uvloop. I'll fix asyncio & uvloop to raise an error if you use them for server sockets too.

The idea is that when you use `create_server` or `create_connection`, the loop has some state in addition to underlying sockets. Part of that state, is the assumption that the sockets state is fully controlled by the loop. If you try to interfere with low-level API, you can get the loop into an undefined state.

In uvloop when you do such things you can easily get a segfault in libuv, because it assumes that you'd never use different APIs on the same socket.

I suggest you to re-implement `create_server` in your framework (it's a relatively simple method). Then you can pass accepted sockets to other processes, and use `connect_accepted_socket` API to wrap them in transports.

**Comment by lsbardel** [comment]
> I suggest you to re-implement create_server in your framework (it's a relatively simple method)

I was trying to avoid doing that :wink:
Anyway, as I said above, this is no longer an issue for me. Thanks for looking into it.
