### ISSUE TITLE
Exception in callback UVTransport._start_reading

### ISSUE THREAD

**Issue by livercat** [MagicStack/uvloop#68]
* **uvloop version**: 0.6.7, 0.7.0
* **python version**: 3.5.2, 3.6
* **platform**: Windows 10, CentOS 7

My application is sending ~300 POST requests per second to an HTTPS url, using asyncio + uvloop + aiohttp.
Occasionally i get the following stack trace:

> Future exception was never retrieved
> future: <Future finished exception=RuntimeError('unable to perform operation on <TCPTransport closed=True reading=False 0xaf80d58>; the handler is closed',)>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/asyncio/sslproto.py", line 578, in _on_handshake_complete
>     raise handshake_exc
>   File "/usr/local/lib/python3.6/asyncio/sslproto.py", line 643, in _process_write_backlog
>     self._transport.write(chunk)
>   File "uvloop/handles/stream.pyx", line 632, in uvloop.loop.UVStream.write (uvloop/loop.c:71069)
>   File "uvloop/handles/handle.pyx", line 150, in uvloop.loop.UVHandle._ensure_alive (uvloop/loop.c:51924)
> RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0xaf80d58>; the handler is closed
> Exception in callback UVTransport._start_reading
> handle: <Handle UVTransport._start_reading>
> Traceback (most recent call last):
>   File "uvloop/cbhandles.pyx", line 52, in uvloop.loop.Handle._run (uvloop/loop.c:46028)
>   File "uvloop/handles/stream.pyx", line 257, in uvloop.loop.UVStream._start_reading (uvloop/loop.c:67301)
>   File "uvloop/handles/handle.pyx", line 150, in uvloop.loop.UVHandle._ensure_alive (uvloop/loop.c:51924)
> RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0xaf80d58>; the handler is closed
> Fatal error on SSL transport
> protocol: <asyncio.sslproto.SSLProtocol object at 0x7f0e29e4aa20>
> transport: <TCPTransport closed=True reading=False 0xaf80d58>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/asyncio/sslproto.py", line 636, in _process_write_backlog
>     self._on_handshake_complete)
>   File "/usr/local/lib/python3.6/asyncio/sslproto.py", line 128, in do_handshake
>     raise RuntimeError('handshake in progress or completed')
> RuntimeError: handshake in progress or completed

I'm not sure this error is caused by uvloop, or if it's merely surfaced here, but I would appreciate any pointers for further investigation. Since the stack trace doesn't have any mention of my actual app code, I'm at a loss where to dig.

**Comment by 1st1** [comment]
Uvloop uses asyncio implementation of ssl, so it's very likely an asyncio bug. Can you reproduce this without uvloop?

**Comment by livercat** [comment]
Should I try to reproduce the issue without uvloop, or does the commit above resolve it in any case?
Thank you.

**Comment by livercat** [comment]
I was able to reproduce the RuntimeError in asyncio without uvloop. Closing this issue.
Thank you.

**Comment by livercat** [comment]
Update: this issue manifested when aiohttp tried to cleanup closed SSL transports. This was default behavior until aiohttp 2.0.5, and doesn't reproduce after. To avoid this issue with earlier versions of aiohttp, set disable_cleanup_closed=False when creating the TCPConnector.

**Comment by 1st1** [comment]
Does this mean that there's a bug in CPython ssl or asyncio/sslproto?

**Comment by livercat** [comment]
> Does this mean that there's a bug in CPython ssl or asyncio/sslproto?
Judging by the comment in the aiohttp cleanup routine, it might be a bug in asyncio:
`:param tuple enable_cleanup_closed: Some ssl servers do not properly complete ssl shutdown process, in that case asyncio leaks ssl connections. If this parameter is set to True, aiohttp additionally aborts underlining transport after 2 seconds. It is off by default.`

**Comment by 1st1** [comment]
OK, I now remember that it's a known issue. We'll fix this in 3.7 or even next 3.6 bugfix release.

**Comment by livercat** [comment]
Awesome, thank you!
