### ISSUE TITLE
Mismatch between port arguments to the asyncio and uvloop loop.create_server method 

### ISSUE THREAD

**Issue by claws** [MagicStack/uvloop#7]
There appears to be a discrepancy in valid `port` arguments to the event loop's `create_server` method. With `asyncio` I can use `0` and `None` to obtain a server bound to an ephemeral port. With `uvloop` it appears that `None` is invalid and raises an error from the `_getaddrinfo` method.

```
File "uvloop/loop.pyx", line 1026, in create_server (uvloop/loop.c:19287)
File "uvloop/loop.pyx", line 505, in uvloop.loop.Loop._getaddrinfo (uvloop/loop.c:11976)
TypeError: port must be a str, bytes or int
```
I came across this because in my use case I create many servers on ephemeral ports that then register their actual bound endpoint details with a service discovery mechanism. In my `asyncio` based implementation I leave the port at its default value (e.g. `port=None`) but this failed when I was testing switching over to `uvloop`. I was able to modify my code to explicitly use `port=0` to get it to work with both event loops.

It would be nice if `uvloop` was a true drop in replacement for `asyncio`. I expect that a check in the [_getaddrinfo](https://github.com/MagicStack/uvloop/blob/master/uvloop/loop.pyx#L495) method could accomodate this discrepancy.

I have created a short [gist](https://gist.github.com/claws/213d0f86a6ef9f6f92b82c5fcb97ae95) that can be used to demonstrate the difference.

**Comment by 1st1** [comment]
The PR is merged, closing this one. Thanks a lot for the contribution!
