### ISSUE TITLE
Need advice: is it really stupid to assign some variables to loop ?

### ISSUE THREAD

**Issue by vladyslav2** [MagicStack/uvloop#72]
I'm not sure it is right thing to do, but i cannot dig any information about, so i just decide to ask.

Lets say for each request i need to create db connection and pass that connection to each function that need data from db.

I came to idea that i can do this:
```
    loop = uvloop.new_event_loop()
    loop.db_conn = await db_connect()
```

and then everywhere i would need db connection i can do this:
```
loop  = async.get_event_loop()
await loop.db_conn.acquire() as conn:
  conn.execute()
```

i tried - that does not work in that way. So i wonder should i work more with that idea or that really really stupid thing to do ?

thanks for you time and answer 
and thanks for that really great product !

**Comment by 1st1** [comment]
Yeah, I don't think that the loop is a best place for a global context data. But I'm not sure what to advice to use instead, since there is no decent local-coroutine-storage sort of library or solution at the moment. Maybe in 3.7 we'll have a solution for this in asyncio core.
