### ISSUE TITLE
Outbound connection performance

### ISSUE THREAD

**Issue by jasonab** [MagicStack/uvloop#73]
Python 3.6, Uvloop 0.7.2

I've been running a Sanic server for some time as an event collector, and its performance has been amazing compared to regular Python. I'd like to expand my usage of Sanic/uvloop to some of my other servers, including my API Gateway, so I wrote a small prototype to test it. My gateway mostly makes Redis calls to assemble a JSON payload for return. What I've found is that its performance is the same as, or worse than, my sync Falcon version (this was using aioredis).

Looking around, I found aredis (https://github.com/NoneGG/aredis), whose benchmarks tell the same story: uvloop performance with Redis is better than asyncio, but no better than sync redis. What I'm unsure of is whether this is an implementation issue (given the performance of asyncpg), or if there are known issues with outbound TCP connections compared to inbound ones?

If MagicStack could produce a performant version of a Redis client, that would be a huge boon.

**Comment by 1st1** [comment]
> What I'm unsure of is whether this is an implementation issue (given the performance of asyncpg), or if there are known issues with outbound TCP connections compared to inbound ones?

It is an issue of the implementation. Couple of things I found:

*  aredis uses streams, a high-level IO abstraction. You can get much more performance using the low-level `asyncio.Protocol`, like asyncpg does.

* It seems that aredis uses text protocol, not binary.

* No Cython optimizations.

> If MagicStack could produce a performant version of a Redis client, that would be a huge boon.

We don't need a fast Redis client for ourselves at the moment, hence no plans to develop it. Although, this can be changed if someone wishes to sponsor the development.

**Comment by jasonab** [comment]
Appreciate the feedback, I'll look into making those suggestions to aredis.

**Comment by jettify** [comment]
Sync database clients usually faster on localhost (if implemented properly), since there is no coroutine/event loop overhead, but when we have network with concurrent clients, this is where async stuff begin to shine.
