### ISSUE TITLE
Can uvloop help performance if I don't use sockets or http ?

### ISSUE THREAD

**Issue by stuaxo** [MagicStack/uvloop#74]
Hi,
   I use asyncio along with aiozmq and lots of   yielding from @asyncio.coroutines for a non-webapp.

All the benchmarks seem to mention using sockets + http.   
Will I see any benefits from uvloop for my non-web-based app ?

S

**Comment by 1st1** [comment]
You should, uvloop have a faster event loop/IO selector implementations.

**Comment by stuaxo** [comment]
Awesome, cheers - I'll give it a go :)
