### ISSUE TITLE
asyncio.TimeHandle is not supported

### ISSUE THREAD

**Issue by fafhrd91** [MagicStack/uvloop#75]
got this in tests

```
    def _timer_handle_cancelled(self, handle):
        """Notification that a TimerHandle has been cancelled."""
>       raise NotImplementedError
E       NotImplementedError
```

**Comment by 1st1** [comment]
Can you provide a snippet to reproduce this?

Overall I think it's normal. `asyncio.TimeHandle` is an implementation detail of asyncio. In general, you shouldn't expect some private asyncio classes to be supported in uvloop and vice versa.

**Comment by fafhrd91** [comment]
i am fine with that. one problem is public name `asyncio.TimeHandle`

**Comment by 1st1** [comment]
Right. I think I can easily add support for them, but since this is the first time I see this bug, I'd wait until more people complain. Thanks!

**Comment by graingert** [comment]
see also https://github.com/MagicStack/uvloop/issues/482
