### ISSUE TITLE
Fatal Error: Missing loop.o

### ISSUE THREAD

**Issue by Sniedes722** [MagicStack/uvloop#79]
* **uvloop version: 0.8.0**:
* **python version: 3.5.2**:
* **platform: Linux x86-64**:

When trying to build the loop extension, I get the following error:

----->

building 'uvloop.loop' extension

creating build/temp.linux-x86_64-3.5

creating build/temp.linux-x86_64-3.5/uvloop

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/ubuntu/workspace/.venv/include/python3.5m -I/home/ubuntu/workspace/.venv/build/uvloop/vendor/libuv/include -c uvloop/loop.c -o build/temp.linux-x86_64-3.5/uvloop/loop.o -O2

Assembler messages:

Fatal error: can't create build/temp.linux-x86_64-3.5/uvloop/loop.o: No such file or directory

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

<-------

Any Help??

**Comment by Sniedes722** [comment]
The loop compiles fine when I install sanic using package installer. however, trying to independently build the loop through pip does not.

**Comment by 1st1** [comment]
Sorry I didn't look into this promptly. Were you able to resolve the issue?

**Comment by Sniedes722** [comment]
@1st1 yup builds fine for 3.5.2 & 3.6.0. Thanks.

**Comment by 1st1** [comment]
Great! Thanks!
