### ISSUE TITLE
Error installing uvloop via pip for PyPy3.5 v5.7.0 

### ISSUE THREAD

**Issue by btegs** [MagicStack/uvloop#82]
* **uvloop version**:
* **python version**:
* **platform**:

I recently downloaded a standalone Linux 64-bit binary of the new [PyPy3.5 v5.7.0](https://bitbucket.org/pypy/pypy/downloads/pypy3-v5.7.0-linux64.tar.bz2) and after installing the latest version of pip via the [get-pip.py](https://bootstrap.pypa.io/get-pip.py) script, I immediately went to install uvloop 0.8 as the next package directly from pip.

I'm not 100% sure if uvloop is meant to run in PyPy3, but I attached a text file with my complete output. I am running Ubuntu 16.04 64-bit and I have installed uvloop directly and as part of Sanic on my system's Python 3.5 and 3.6.

[uvloop_pypy35.txt](https://github.com/MagicStack/uvloop/files/876436/uvloop_pypy35.txt)

**Comment by 1st1** [comment]
PyPy isn't yet supported, sorry.

**Comment by btegs** [comment]
Is this something PyPy needs to work out or is this an issue the uvloop team will investigate?

**Comment by 1st1** [comment]
We'll likely have to rewrite most of the code to use cffi (not cython), so it's not a quick fix. You should be able to use vanilla asyncio on PyPy, which should be quite a bit faster than vanilla asyncio on CPython.

**Comment by btegs** [comment]
So what would the solution be down the road? Converting uvloop away from Cython to cffi or to have a fork of uvloop that is cffi that can be run by PyPy3?

**Comment by 1st1** [comment]
First, I would want to write some benchmarks to see if uvloop even needs to be ported to PyPy. Maybe vanilla asyncio is fast enough on it. That means that I'll need a basic trimmed down version of CFFI-ed uvloop enough to run an echo server benchmark.

Second, if it does make sense to port uvloop to PyPy, then most likely we can convert 60-90% of the code to use CFFI for both CPython and PyPy (without performance degradation for the former). Remaining performance critical parts can be written in both CFFI & Cython. I definitely don't want to fork uvloop or copy/paste huge chunks of code.

**Comment by TiberiumN** [comment]
@1st1 see this - https://github.com/koehlma/uv
