### ISSUE TITLE
'sockname' is different when using uvloop compared to asyncio's built-in event loop

### ISSUE THREAD

**Issue by frederikaalund** [MagicStack/uvloop#85]
* **uvloop version**: 0.8.0
* **Python version**: 3.5.2
* **Platform**: Linux 4.4 / buildroot
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: Yes

The following program can be used to re-produce the issue.

    import asyncio

    # Toggle to use uvloop
    use_uvloop = True
    if use_uvloop:
        import uvloop
        asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

    loop = asyncio.get_event_loop()

    async def print_local_ip():
        # Get and print the local IP
        transport, protocol = await loop.create_datagram_endpoint(
            asyncio.DatagramProtocol,
            remote_addr=('8.8.8.8', 80))
        local_ip = transport.get_extra_info('sockname')[0]
        print('local_ip: {}'.format(local_ip))

    loop.run_until_complete(print_local_ip())

The above program prints `192.168.1.108` when using the built-in event loop. However, when using uvloop, the same program prints `0.0.0.0`.

**Comment by 1st1** [comment]
I'll take a look into this. For now you should be able to use this workaround:

```python
sock = transport.get_extra_info('socket')
local_ip = sock.getsockname()
```

**Comment by frederikaalund** [comment]
For the record, the workaround does not work. `local_ip` contains `('0.0.0.0', 34252)`.

**Comment by 1st1** [comment]
Fixed in master. Will be in the next release (soon)

**Comment by frederikaalund** [comment]
Thank you very much. I'll try the master branch on Monday.

**Comment by 1st1** [comment]
Please try uvloop v0.9.0, where this bug should be fixed.

**Comment by frederikaalund** [comment]
Works here, thanks!
