### ISSUE TITLE
Question: Unclear Benchmark Results on GitHub and on the blog

### ISSUE THREAD

**Issue by boramalper** [MagicStack/uvloop#89]
I'm confused while comparing the benchmark results on GitHub and the website. On GitHub, there are results for `asyncio/uvloop sockets/streams/protocol` but on the blog only `asyncio/uvloop streams/NONE` listed. Does `uvloop` [here on the blog](https://magic.io/blog/uvloop-blazing-fast-python-networking/) mean `uvloop protocol` or what?

Thanks!

**Comment by 1st1** [comment]
> Does uvloop here on the blog mean uvloop protocol or what?

Yes.

**Comment by ronindesign** [comment]
<disregard>
