### ISSUE TITLE
Compat for Python 2.7

### ISSUE THREAD

**Issue by breerly** [MagicStack/uvloop#9]
Would love to look at adopting uvloop in a number of high-scale tornado apps we have in production. Those are running Python 2.7 - what's stopping this library from adding support?

**Comment by 1st1** [comment]
uvloop implements an asyncio-compliant event loop. It will have to be heavily reengineered to support both asyncio and Tornado (basically we'll have to re-implement a lot of Tornado in uvloop), and unfortunately, I don't have resources to do that.

**Comment by ZetaHunter** [comment]
What's stopping you from porting your apps to 3.5+ instead?

**Comment by breerly** [comment]
Tornado has a asyncio bridge though.

**Comment by 1st1** [comment]
> Tornado has a asyncio bridge though.

Didn't know about that. I think that bridge is only operational under Python 3, though, since asyncio requires at least 3.3.

**Comment by breerly** [comment]
> asyncio requires at least 3.3

That's right. I'm going to play with uvloop, tornado, & trollius (asyncio to 2.7 port).

Will followup.

**Comment by GMLudo** [comment]
to my knowledge, trollius is deprecated.

I don't know your codebase, however, it should less "dangerous" / more stable way to migrate first your source code to python 3 with tornado.

**Comment by breerly** [comment]
Fair point, thanks

**Comment by schlamar** [comment]
@breerly Have you seen https://github.com/saghul/tornaduv
