### ISSUE TITLE
Can't UDP sendto named host

### ISSUE THREAD

**Issue by richardkiss** [MagicStack/uvloop#91]
* **uvloop v0.80**:
* **Python 3.6.1**:
* **Platform Mac OS X**:
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env? yes**:

In uvloop 0.8.0, an error occurs when sending UDP data to a named host. The default asyncio eventloop allows it (and it probably shouldn't since sendto can block on the name lookup). Here is an example.
```import asyncio
import uvloop


class P:
    def connection_made(self, transport):
        pass


async def go():
    loop = asyncio.get_event_loop()
    pair = await loop.create_datagram_endpoint(P, local_addr=("0.0.0.0", 6666))
    transport = pair[0]
    try:
        transport.sendto(b'foo', ("google.com", 6666))
    except Exception as ex:
        print(ex)

if 1:
    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
asyncio.get_event_loop().run_until_complete(go())
```

**Comment by 1st1** [comment]
Good catch.  I've fixed uvloop to raise an error when a DNS lookup is needed in `.sendto()`. I will fix asyncio in a similar fashion.  The fix will be in the next uvloop release in a couple of days.

**Comment by 1st1** [comment]
Please try uvloop v0.9.0.
