### ISSUE TITLE
New benchmark for uvloop

### ISSUE THREAD

**Issue by srault95** [MagicStack/uvloop#92]
https://github.com/srault95/vmbench/tree/add_features

- uvloop/aiohttp
- Sanic
- Gevent

http://espace-groupware.com/docs/vmbench/report-http.html

The best is ... uvloop !!!

Thank.

**Comment by tonal** [comment]
Can you test for Pothon 3.6.x?

**Comment by alex-eri** [comment]
best was sanic workers. what is "sanic workers"?

**Comment by 1st1** [comment]
Nice! Stay tuned for more improvements in uvloop & asyncio => better performance :)
