### ISSUE TITLE
IDNA encoding of hostname

### ISSUE THREAD

**Issue by Glandos** [MagicStack/uvloop#95]
* **uvloop version**: 0.8.0
* **Python version**: 3.5
* **Platform**: Debian GNU/Linux testing
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: I don't know

Commit 1d5ae0b introduces IDNA encoding. While this is a good solution for FQDN hostnames, this is really a performance killer when sending a lot of small packets using lots of IP address (use case in https://github.com/boramalper/magnetico/issues/92). On my CPU, the IDNA encoding is taking ~5% of the whole program execution, and more than 75% of the `sendto` method call.

The main issue here is that the `sendto` call is done with address given with the call to `datagram_received`, so `uvloop` should be already aware that the hostname is an IP address.
I guess that `datagram_received` cannot return an encoded hostname, but the idea is here.

**Comment by asvetlov** [comment]
You could skip encoding by sending `host` parameter as bytes, isn't it?

**Comment by Glandos** [comment]
Yes, but the `host` parameter is the one received from `datagram_received`, so it theoretically could be a FQDN.

**Comment by 1st1** [comment]
> EDIT: I don't know if there is a fast test to tell if the host is an IP address or not.

Yes, there's a fast test. I'll look into this.

**Comment by 1st1** [comment]
Fixed in master. Will be in 0.9.0 release (soon)

**Comment by 1st1** [comment]
Please try uvloop v0.9.0.
